import type { Type } from 'arktype';

import type { AnyKubernetesObject, AnyResourceDefinition, Applik8sError, ArkTypeSchemaSource, CapabilityClientSet, CapabilityDescriptor, CapabilityKind, CustomSchemaSource, EffectPolicy, HandlerRegistrationForResources, JsonObject, JsonSchemaSource, KubernetesObject, OperatorDefinition, OperatorDeploymentOptions, PermissionRule, ResourceDefinition, ResourceObject, Result, RuntimeConfig, RuntimeSchema, SecretRef, StatusConvention } from '@applik8s/core';

export type SchemaInput<T extends object> = Type<T> | RuntimeSchema<T> | ArkTypeSchemaSource<T> | JsonSchemaSource<T> | CustomSchemaSource<T>;
export interface CrdOptions<TSpec extends object, TStatus extends object> { readonly apiVersion: string; readonly kind: string; readonly plural?: string; readonly scope?: 'Namespaced' | 'Cluster'; readonly spec: SchemaInput<TSpec>; readonly status?: SchemaInput<TStatus>; readonly statusConvention?: StatusConvention; readonly additionalPrinterColumns?: ResourceDefinition<TSpec, TStatus>['additionalPrinterColumns']; }
export interface SchemaAdapterApi { fromArkType<T extends object>(source: ArkTypeSchemaSource<T>): Result<RuntimeSchema<T>>; fromJsonSchema<T extends object>(source: JsonSchemaSource<T>): Result<RuntimeSchema<T>>; fromCustom<T extends object>(source: CustomSchemaSource<T>): Result<RuntimeSchema<T>>; }
export type ResourceDefinitionMap<TCapabilities extends CapabilityClientSet = CapabilityClientSet> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>;
export type ErasedCrdInstanceInput = CrdInstanceInput<object>;
export type CrdInstanceFactoryConstraint = (input: never) => KubernetesObject<object, object>;
export type AnyCrdInstanceFactory = (input: ErasedCrdInstanceInput) => AnyKubernetesObject;
export type CrdFactoryConstraintMap = Readonly<Record<string, CrdInstanceFactoryConstraint>>;
export type AnyCrdFactoryMap = Readonly<Record<string, AnyCrdInstanceFactory>>;
export type CrdFactoryAliasMap<TFactories extends CrdFactoryConstraintMap = AnyCrdFactoryMap> = { readonly [K in keyof TFactories as K extends string ? Uncapitalize<K> : never]: TFactories[K] };
export type DeployedCrdFactoryMap<TFactories extends CrdFactoryConstraintMap = AnyCrdFactoryMap> = TFactories & CrdFactoryAliasMap<TFactories>;
export type CrdFactoryInput<TFactory> = TFactory extends (input: infer TInput) => KubernetesObject<object, object> ? [TInput] extends [never] ? ErasedCrdInstanceInput : TInput : ErasedCrdInstanceInput;
export type CrdFactoryOutput<TFactory> = TFactory extends (input: never) => infer TOutput ? TOutput : KubernetesObject<object, object>;
export type CrdFactoryForResource<TResource> = TResource extends ResourceDefinition<infer TSpec, infer TStatus, infer _TCapabilities> ? CrdInstanceFactory<TSpec, TStatus> : CrdInstanceFactory;
export type CrdFactoryMap<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends ResourceDefinitionMap<TCapabilities> = ResourceDefinitionMap<TCapabilities>> = { readonly [K in keyof TResources]: CrdFactoryForResource<TResources[K]> };
export interface OperatorOptions<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends ResourceDefinitionMap<TCapabilities> = ResourceDefinitionMap<TCapabilities>> { readonly name: string; readonly resources: TResources; readonly handlers: readonly HandlerRegistrationForResources<TResources, TCapabilities>[]; readonly capabilities?: Readonly<Record<keyof TCapabilities & string, CapabilityDescriptor>>; readonly permissions?: readonly PermissionRule[]; readonly deployment?: OperatorDeploymentOptions; readonly runtime?: RuntimeConfig; readonly trustLevel?: OperatorDefinition<TCapabilities>['trustLevel']; readonly effects?: EffectPolicy; }
export interface CallableOperator<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends ResourceDefinitionMap<TCapabilities> = ResourceDefinitionMap<TCapabilities>> { (options: OperatorDeploymentOptions): DeployedOperator<TCapabilities, CrdFactoryMap<TCapabilities, TResources>, TResources>; readonly definition: OperatorDefinition<TCapabilities, TResources>; }
export type DeployedOperator<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TFactories extends CrdFactoryConstraintMap = AnyCrdFactoryMap, TDefinitions extends ResourceDefinitionMap<TCapabilities> = ResourceDefinitionMap<TCapabilities>> = { readonly definition: OperatorDefinition<TCapabilities, TDefinitions>; readonly namespace?: string; readonly crdFactories: DeployedCrdFactoryMap<TFactories>; readonly resources: DeployedCrdFactoryMap<TFactories>; resource<TKey extends keyof DeployedCrdFactoryMap<TFactories> & string>(kind: TKey, input: CrdFactoryInput<DeployedCrdFactoryMap<TFactories>[TKey]>): CrdFactoryOutput<DeployedCrdFactoryMap<TFactories>[TKey]>; } & DeployedCrdFactoryMap<TFactories>;
export type CrdInstanceFactory<TSpec extends object = JsonObject, TStatus extends object = JsonObject> = (input: CrdInstanceInput<TSpec>) => ResourceObject<TSpec, TStatus>;
export interface CrdInstanceInput<TSpec extends object = JsonObject> { readonly name: string; readonly namespace?: string; readonly spec: TSpec; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
export interface ExternalCapabilityFactory { http(options: HttpCapabilityOptions): CapabilityDescriptor; cloudApi(options: EndpointCapabilityOptions): CapabilityDescriptor; database(options: EndpointCapabilityOptions): CapabilityDescriptor; queue(options: EndpointCapabilityOptions): CapabilityDescriptor; objectStore(options: EndpointCapabilityOptions): CapabilityDescriptor; identity(options: EndpointCapabilityOptions): CapabilityDescriptor; }
export interface HttpCapabilityOptions { readonly baseUrl: string; readonly auth?: SecretRef | 'serviceAccount' | 'none'; readonly timeoutMs?: number; }
export interface EndpointCapabilityOptions { readonly endpoint: string; readonly auth?: SecretRef | 'serviceAccount' | 'none'; readonly timeoutMs?: number; readonly kind?: CapabilityKind; }
export type CrdFunction = <TSpec extends object, TStatus extends object>(options: CrdOptions<TSpec, TStatus>) => ResourceDefinition<TSpec, TStatus>;
export type OperatorFunction = <TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends ResourceDefinitionMap<TCapabilities> = ResourceDefinitionMap<TCapabilities>>(options: OperatorOptions<TCapabilities, TResources>) => CallableOperator<TCapabilities, TResources>;
export type SecretRefFunction = (name: string, key: string, namespace?: string) => SecretRef;
export type IsApplik8sErrorFunction = (value: unknown) => value is Applik8sError;
export interface Applik8sSdk { readonly crd: CrdFunction; readonly operator: OperatorFunction; readonly secretRef: SecretRefFunction; readonly schema: SchemaAdapterApi; readonly external: ExternalCapabilityFactory; readonly isApplik8sError: IsApplik8sErrorFunction; }
export type PublicApiResult<T> = Result<T>;
