FROM rust:1-bookworm@sha256:7d0723df719e7f213b69dc7c8c595985c3f4b060cfbee4f7bc0e347a86fe3b6a AS builder

WORKDIR /workspace
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
RUN cargo build --release -p applik8s-operator-host

FROM debian:bookworm-slim@sha256:60eac759739651111db372c07be67863818726f754804b8707c90979bda511df

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /operator-runtime /etc/applik8s /handler \
  && chown -R 65532:65532 /operator-runtime /etc/applik8s /handler

COPY --from=builder --chown=65532:65532 /workspace/target/release/applik8s-operator-host /operator-runtime/applik8s-operator-host

WORKDIR /operator-runtime
USER 65532:65532
ENTRYPOINT ["/operator-runtime/applik8s-operator-host"]
