import { describeCharacterSuite, type CharacterScenario } from '../../testing/test/character.js';

const s = (name: string, userStory: string, arrange: readonly string[], act: readonly string[], assert: readonly string[]): CharacterScenario => ({ name, userStory, arrange, act, assert });

describeCharacterSuite('TypeKro adapter character tests', [
  s('adapts an applik8s operator into a callable TypeKro composition', 'As a TypeKro user, I install operators like components.', ['Define imagePipeline operator and compiled manifest.'], ['Call typeKro.composition(imagePipeline.definition, manifest, { compositionName }).'], ['The result is callable and exposes operator, manifest, composition, graph, crdFactories, and factory methods.']),
  s('calling an adapted composition returns install resource and CRD factories', 'As a TypeKro user, I instantiate operator CRDs from the installed component.', ['Adapt imagePipeline.'], ['Call pipeline = mediaPipeline({ namespace: "media", replicas: 2 }).'], ['pipeline exposes ImageJob, imageJob, resources, and crdFactories returning Enhanced resources.']),
  s('supports direct and Kro factory modes', 'As a TypeKro user, I choose deployment style without changing applik8s operator authoring.', ['Adapt an operator.'], ['Call factory("direct") and factory("kro").'], ['Both factories create resources with the expected TypeKro mode.']),
  s('adapted CRD status composes with other TypeKro resources', 'As a composition author, I drive infrastructure from operator status.', ['Create image = pipeline.imageJob(...).'], ['Use image.status.phase in a TypeKro status expression.'], ['The expression is type-compatible and preserved in the graph.']),
  s('wraps a TypeKro graph as an applik8s operation target', 'As a handler author, I can apply TypeKro desired resources from reconciliation.', ['Define tenantStack TypeKro graph.'], ['Call typeKro.targetFactory(tenantStack)(tenant.spec).'], ['The target can be passed directly to `ctx.apply()`, `ctx.delete()`, proxy `resource.apply()`, and proxy `resource.delete()`.']),
  s('applies TypeKro operation targets from proxy handlers', 'As a handler author, I use tenant.apply(stack) ergonomically.', ['Create Tenant.on.reconcile handler applying a TypeKro target.'], ['Run the handler.'], ['The normalized plan contains TypeKro-rendered apply operations.']),
  s('deletes TypeKro operation targets from finalizers', 'As a handler author, I clean up graph resources during deletion.', ['Create Tenant.on.deleted handler deleting a TypeKro target.'], ['Run the handler.'], ['The normalized plan contains TypeKro-rendered delete operations.']),
  s('renders plans without live effects', 'As a test/debug user, I inspect TypeKro operations before applying them.', ['Create an operation target.'], ['Call resource.plan(target).'], ['A normalized plan is returned and no Kubernetes effects occur.']),
  s('maps TypeKro status into handler status', 'As an integration author, I bridge graph status into CRD status.', ['Graph status differs from handler status shape.'], ['Create graph adapter with statusMapper.'], ['renderStatus returns the mapped handler status.']),
  s('requires a status mapper when status shapes differ', 'As a type-safety user, I cannot accidentally assign incompatible status.', ['Graph status and handler CRD status are incompatible.'], ['Create graph adapter without statusMapper.'], ['The type system or adapter rejects the configuration.']),
  s('infers RBAC from TypeKro resources', 'As a cluster admin, I inspect permissions for graph operations.', ['TypeKro graph renders Deployment, Service, and ConfigMap.'], ['Call inferRbac(graph).'], ['Permissions include apply/read/delete needs for rendered resources.']),
  s('integrates owner references where Kubernetes allows them', 'As an operator author, child resources follow parent ownership rules.', ['Apply TypeKro target with owner options.'], ['Render apply plan.'], ['Rendered Kubernetes objects include valid owner refs when allowed and omit invalid owner refs.']),
]);
