import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { buildImplicitRuntimeImage } from '@applik8s/compiler';
import type { OperatorManifest } from '@applik8s/core';
import { afterAll, beforeAll, expect, it } from 'vitest';

import { assertExpectedKubectlContext, describeLive, docker, exec, formatSettledOutput, kubectl } from './live-e2e-helpers';

const namespace = process.env.APPLIK8S_E2E_NAMESPACE ?? `applik8s-typekro-direct-call-${process.pid}`;
const group = `media${process.pid}.applik8s.dev`;
const operatorName = 'direct-call-image-pipeline';
const imageJobName = 'direct-call-hero';

let tempDir: string | undefined;
let outDir: string | undefined;

describeLive('live TypeKro direct-call composition build', () => {
  beforeAll(async () => {
    await assertExpectedKubectlContext();

    await docker(['build', '--file', 'Dockerfile.operator-host', '--tag', 'ghcr.io/applik8s/applik8s-operator-host:dev', '.'], process.cwd());
    await kubectl(['create', 'namespace', namespace]);

    tempDir = await mkdtemp(join(tmpdir(), 'applik8s-typekro-direct-call-'));
    outDir = join(tempDir, 'dist');
    const entrypoint = join(tempDir, 'media-stack.ts');
    await writeFile(entrypoint, mediaStackSource(group, namespace));

    await exec('bun', ['run', 'applik8s', 'build', entrypoint, '--typekro', '--composition-name', 'mediaStack', '--out-dir', outDir], process.cwd());

    for (const manifestPath of await nestedOperatorManifestPaths()) {
      const manifest = await readOperatorManifest(manifestPath);
      const image = await buildImplicitRuntimeImage({ manifest });
      if (!image.ok) {
        throw new Error(image.error.message);
      }
    }
  }, 600_000);

  afterAll(async () => {
    if (process.env.APPLIK8S_E2E_LIVE === '1') {
      await kubectl(['delete', 'namespace', namespace, '--ignore-not-found=true', '--wait=false']);
      await kubectl(['delete', 'crd', `imagejobs.${group}`, '--ignore-not-found=true', '--wait=false']);
    }
    if (tempDir && process.env.APPLIK8S_KEEP_TMP !== '1') {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it('installs the direct-called operator and reconciles the generated CRD instance', async () => {
    await runGeneratedTypeKroApplyScript();

    await kubectl(['wait', `crd/imagejobs.${group}`, '--for=condition=Established', '--timeout=60s']);
    await rolloutStatusWithDiagnostics();
    await waitForImageJobPhase('Processing');

    expect((await kubectl(['get', `imagejobs.${group}/${imageJobName}`, '--namespace', namespace, '--output=jsonpath={.status.outputUrls[0]}'])).stdout.trim()).toBe(`s3://images/${imageJobName}.png.webp`);
  }, 300_000);
});

async function nestedOperatorManifestPaths(): Promise<readonly string[]> {
  const manifestPath = join(requiredOutDir(), 'typekro', 'typekro-composition.json');
  // typecast: composition bundle JSON is generated by applik8s; this test validates only the operator manifest references it needs.
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as { readonly spec?: { readonly operators?: readonly { readonly manifest?: string }[] } };
  const paths = manifest.spec?.operators?.map((operator) => operator.manifest).filter((path): path is string => typeof path === 'string') ?? [];
  if (paths.length === 0) {
    throw new Error(`TypeKro composition manifest did not reference nested operator manifests: ${manifestPath}`);
  }
  return paths;
}

async function readOperatorManifest(path: string): Promise<OperatorManifest> {
  // typecast: nested operator manifest JSON is generated by the compiler and consumed immediately by the runtime image builder.
  return JSON.parse(await readFile(path, 'utf8')) as OperatorManifest;
}

async function runGeneratedTypeKroApplyScript(): Promise<void> {
  await exec('sh', [join(requiredOutDir(), 'typekro', 'apply.sh')], process.cwd());
}

async function rolloutStatusWithDiagnostics(): Promise<void> {
  try {
    await kubectl(['rollout', 'status', `deployment/${operatorName}`, '--namespace', namespace, '--timeout=180s']);
  } catch (cause) {
    const diagnostics = await Promise.allSettled([
      kubectl(['describe', `deployment/${operatorName}`, '--namespace', namespace]),
      kubectl(['get', 'pods', '--namespace', namespace, '--selector', `app.kubernetes.io/name=${operatorName}`, '--output=wide']),
      kubectl(['describe', 'pods', '--namespace', namespace, '--selector', `app.kubernetes.io/name=${operatorName}`]),
      kubectl(['logs', '--namespace', namespace, '--selector', `app.kubernetes.io/name=${operatorName}`, '--all-containers=true', '--tail=300']),
      kubectl(['get', 'events', '--namespace', namespace, '--sort-by=.lastTimestamp']),
    ]);
    throw new Error(`${cause instanceof Error ? cause.message : 'Rollout failed.'}\n${diagnostics.map(formatSettledOutput).join('\n')}`);
  }
}

async function waitForImageJobPhase(phase: string): Promise<void> {
  try {
    await kubectl(['wait', `imagejobs.${group}/${imageJobName}`, '--namespace', namespace, `--for=jsonpath={.status.phase}=${phase}`, '--timeout=180s']);
  } catch (cause) {
    const diagnostics = await Promise.allSettled([
      kubectl(['get', `imagejobs.${group}/${imageJobName}`, '--namespace', namespace, '--output=yaml']),
      kubectl(['logs', '--namespace', namespace, '--selector', `app.kubernetes.io/name=${operatorName}`, '--all-containers=true', '--tail=500']),
      kubectl(['get', 'events', '--namespace', namespace, '--sort-by=.lastTimestamp']),
    ]);
    throw new Error(`${cause instanceof Error ? cause.message : `Expected ImageJob phase ${phase}.`}\n${diagnostics.map(formatSettledOutput).join('\n')}`);
  }
}

function requiredOutDir(): string {
  if (!outDir) {
    throw new Error('TypeKro direct-call e2e output directory was not initialized.');
  }
  return outDir;
}

function mediaStackSource(apiGroup: string, targetNamespace: string): string {
  return `import { type } from 'arktype';
import { sdk, typeKro } from '@applik8s/applik8s';

interface ImageSpec { sourceUrl: string; formats: string[] }
interface ImageStatus { phase?: 'Processing'; outputUrls?: string[] }

const spec = {
  kind: 'jsonSchema' as const,
  ref: { kind: 'jsonSchema' as const, exportName: 'ImageSpec' },
  schema: {
    type: 'object',
    required: ['sourceUrl', 'formats'],
    additionalProperties: false,
    properties: {
      sourceUrl: { type: 'string' },
      formats: { type: 'array', items: { type: 'string' } },
    },
  },
};
const status = {
  kind: 'jsonSchema' as const,
  ref: { kind: 'jsonSchema' as const, exportName: 'ImageStatus' },
  schema: { type: 'object', properties: { phase: { type: 'string' }, outputUrls: { type: 'array', items: { type: 'string' } } } },
};

export const ImageJob = sdk.crd<ImageSpec, ImageStatus>({ apiVersion: ${JSON.stringify(`${apiGroup}/v1alpha1`)}, kind: 'ImageJob', spec, status });
export const imagePipeline = sdk.operator({
  name: ${JSON.stringify(operatorName)},
  deployment: { namespace: ${JSON.stringify(targetNamespace)}, replicas: 1 },
  resources: { ImageJob },
  handlers: [],
});

export const mediaStack = typeKro.kubernetesComposition({
  name: 'direct-call-media-stack',
  apiVersion: ${JSON.stringify(`${apiGroup}/v1alpha1`)},
  kind: 'DirectCallMediaStack',
  spec: type({}),
  status: type({ ready: 'boolean' }),
}, () => {
  const pipeline = imagePipeline({ namespace: ${JSON.stringify(targetNamespace)}, replicas: 1 });
  const image = pipeline.imageJob({
    name: ${JSON.stringify(imageJobName)},
    namespace: ${JSON.stringify(targetNamespace)},
    spec: { sourceUrl: ${JSON.stringify(`s3://images/${imageJobName}.png`)}, formats: ['webp'] },
  });
  image.on.reconcile((job) => {
    job.status.phase = 'Processing';
    job.status.outputUrls = [job.spec.sourceUrl + '.webp'];
  });
  return { ready: image.status.phase === 'Processing' };
});
`;
}
