import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { guestBookConfigFromEnvironment } from '../guestbook/config.js';

describe('GuestBook launch contract', () => {
  it('keeps the first teaching example short and representative', () => {
    const source = readFileSync(new URL('../guestbook-minimal.ts', import.meta.url), 'utf8');
    const lines = source.split('\n').length;
    expect(lines).toBeGreaterThanOrEqual(100);
    expect(lines).toBeLessThanOrEqual(200);
    expect(source).toContain("application.resource('GuestBook'");
    expect(source).toContain("GuestBookEntry.index('publishedEntries'");
    expect(source.match(/\.on\.reconcile\(/g)).toHaveLength(1);
    expect(source).toContain('application.operator(guestBookController');
    expect(source).toContain("server.get('/'");
    expect(source).toContain("server.post('/entries'");
    expect(source).toContain("application.expose('web'");
  });

  it('resolves local and public deployment inputs once through a typed profile boundary', () => {
    expect(guestBookConfigFromEnvironment({}).profile).toBe('local');
    const publicConfig = guestBookConfigFromEnvironment({
      APPLIK8S_GUESTBOOK_PROFILE: 'public',
      APPLIK8S_GUESTBOOK_DOMAIN: 'guestbook.example.com',
      APPLIK8S_GUESTBOOK_ISSUER_NAME: 'letsencrypt-prod',
      APPLIK8S_GUESTBOOK_ISSUER_KIND: 'ClusterIssuer',
      APPLIK8S_GUESTBOOK_DNS_TTL_SECONDS: '300',
    });
    expect(publicConfig).toMatchObject({
      profile: 'public',
      hostname: 'guestbook.example.com',
      issuerRef: { name: 'letsencrypt-prod', kind: 'ClusterIssuer' },
      dnsTtlSeconds: 300,
    });
    expect(() => guestBookConfigFromEnvironment({ APPLIK8S_GUESTBOOK_PROFILE: 'public' })).toThrow(/requires APPLIK8S_GUESTBOOK_DOMAIN/);
  });

  it('keeps the public demo bounded and precise about the renderer', () => {
    const source = readFileSync(new URL('../guestbook.ts', import.meta.url), 'utf8');
    expect(source).toContain('maxRequestBodyBytes: 4_096');
    expect(source).toContain('mutationRateLimit: { maxRequests: 8, windowSeconds: 60 }');
    expect(source).toContain('limit: 100');
    expect(source).toContain('limit: 2');
    expect(source).toContain('custom TypeScript controller generated by applik8s—not the standard Kubernetes control-plane binaries');
    expect(source).toContain('Inspect the sanitized resource');
    expect(source).not.toMatch(/const\s+CRDs\s*=\s*0/);
  });
});
