import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { renderGuestBookSnapshot } from '../guestbook.js';
import { guestBookConfigFromEnvironment } from '../guestbook/config.js';

describe('GuestBook launch contract', () => {
  it('keeps the first teaching example short and representative', () => {
    const source = readFileSync(new URL('../guestbook-minimal.ts', import.meta.url), 'utf8');
    const lines = source.split('\n').length;
    expect(lines).toBeGreaterThanOrEqual(100);
    expect(lines).toBeLessThanOrEqual(200);
    expect(source).toContain("application.resource('GuestBook'");
    expect(source).toContain("GuestBookEntry.index('publishedEntries'");
    expect(source.match(/\.on\.reconcile\(/g)).toHaveLength(1);
    expect(source).toContain('application.operator(guestBookController');
    expect(source).toContain("server.get('/'");
    expect(source).toContain("server.post('/entries'");
    expect(source).toContain("application.expose('web'");
  });

  it('resolves local and public deployment inputs once through a typed profile boundary', () => {
    expect(guestBookConfigFromEnvironment({}).profile).toBe('local');
    const publicConfig = guestBookConfigFromEnvironment({
      APPLIK8S_GUESTBOOK_PROFILE: 'public',
      APPLIK8S_GUESTBOOK_DOMAIN: 'guestbook.example.com',
      APPLIK8S_GUESTBOOK_ISSUER_NAME: 'letsencrypt-prod',
      APPLIK8S_GUESTBOOK_ISSUER_KIND: 'ClusterIssuer',
      APPLIK8S_GUESTBOOK_DNS_TTL_SECONDS: '300',
    });
    expect(publicConfig).toMatchObject({
      profile: 'public',
      hostname: 'guestbook.example.com',
      issuerRef: { name: 'letsencrypt-prod', kind: 'ClusterIssuer' },
      dnsTtlSeconds: 300,
    });
    expect(() => guestBookConfigFromEnvironment({ APPLIK8S_GUESTBOOK_PROFILE: 'public' })).toThrow(/requires APPLIK8S_GUESTBOOK_DOMAIN/);
  });

  it('keeps the public demo bounded and precise about the renderer', () => {
    const source = readFileSync(new URL('../guestbook.ts', import.meta.url), 'utf8');
    expect(source).toContain('maxRequestBodyBytes: 4_096');
    expect(source).toContain('mutationRateLimit: { maxRequests: 8, windowSeconds: 60 }');
    expect(source).toContain('limit: 100');
    expect(source).toContain('limit: 2');
    expect(source).toContain('custom TypeScript controller generated by applik8s—not the standard Kubernetes control-plane binaries');
    expect(source).toContain('Inspect the sanitized resource');
    expect(source).toContain('app.expose("web"');
    expect(source).toContain('Certificate.certManager');
    expect(source).toContain('DnsPublication.externalDns');
    expect(source).not.toMatch(/const\s+CRDs\s*=\s*0/);
  });

  it('makes the UI deployment profile visible without overstating edge readiness', () => {
    const base = {
      title: 'GuestBook',
      description: 'A live control-plane demo.',
      bookName: 'main',
      namespace: 'guestbook',
      entries: [{ author: 'Ada', message: 'Hello', timestamp: '2026-07-15T00:00:00.000Z' }],
      lastReconciled: '2026-07-15T00:00:00.000Z',
      renderedAt: '2026-07-15T00:00:00.000Z',
    };
    const local = renderGuestBookSnapshot({ ...base, publicUrl: 'http://guestbook.localhost/' });
    const publicPage = renderGuestBookSnapshot({ ...base, publicUrl: 'https://guestbook.example.com/' });

    expect(local).toContain('data-exposure-mode="local-http"');
    expect(local).toContain('Local profile · HTTP only');
    expect(publicPage).toContain('data-exposure-mode="managed-https"');
    expect(publicPage).toContain('Public profile · managed HTTPS requested');
    expect(publicPage).toContain('namespaced cert-manager');
    expect(publicPage).toContain('app.expose(&quot;web&quot;');
    expect(publicPage).toContain('<strong>GuestBook</strong>A live control-plane demo.');
    expect(publicPage).not.toMatch(/DNS (is )?ready/i);
  });
});
