import type { OperatorManifest } from '@applik8s/core';
import { imageRefString } from '@applik8s/typetainer';
import { DEFAULT_OPERATOR_HOST_IMAGE_REFERENCE } from '../operator-host-image.js';
import { typeKroKubectlContextShell } from './application-support.js';
import type { TypeKroCompositionResource } from './index.js';
import { typeKroSchemaApiResources } from './typekro-api-resources.js';
import { shellQuote } from './utilities.js';

export function emitRuntimeImageDockerfile(manifest: OperatorManifest): string {
  const container = manifest.spec.container;
  if (!container?.baseImage || !container.files) {
    throw new Error('Operator manifest is missing the implicit runtime image recipe.');
  }
  const labels = container.build?.labels ?? {};
  const labelLines = Object.entries(labels).map(([key, value]) => `${JSON.stringify(key)}=${JSON.stringify(value)}`);
  const baseImageArgument = ['$', '{APPLIK8S_BASE_IMAGE}'].join('');
  return [
    `ARG APPLIK8S_BASE_IMAGE=${imageRefString(container.baseImage)}`,
    `FROM ${baseImageArgument}`,
    '',
    ...(labelLines.length > 0 ? [`LABEL ${labelLines.join(' ')}`, ''] : []),
    'USER 0:0',
    'RUN mkdir -p /etc/applik8s /handler',
    ...container.files.flatMap((file) => [`COPY --chown=65532:65532 ${file.source} ${file.destination}`, ...(file.mode ? [`RUN chmod ${file.mode} ${file.destination}`] : [])]),
    '',
    'ENV APPLIK8S_MANIFEST_PATH=/etc/applik8s/operator-manifest.json',
    'ENV APPLIK8S_HANDLER_PATH=/handler/handler.wasm',
    'USER 65532:65532',
    '',
  ].join('\n');
}

export function emitStandaloneApplyScript(manifest: OperatorManifest): string {
  const container = manifest.spec.container;
  if (!container?.build?.dockerfile) {
    throw new Error('Operator manifest is missing the implicit runtime image build recipe.');
  }
  const image = imageRefString(container.image);
  const baseImage = container.baseImage ? imageRefString(container.baseImage) : DEFAULT_OPERATOR_HOST_IMAGE_REFERENCE;
  const namespace = manifest.metadata.annotations?.['applik8s.dev/namespace'] ?? '';
  const shDefault = (name: string, fallback: string) => ['$', `{${name}:-${fallback}}`].join('');
  return [
    '#!/usr/bin/env sh',
    'set -eu',
    '',
    'SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"',
    `DOCKER="${shDefault('DOCKER', 'docker')}"`,
    `KUBECTL="${shDefault('KUBECTL', 'kubectl')}"`,
    `DEFAULT_IMAGE=${JSON.stringify(image)}`,
    `IMAGE="${shDefault('APPLIK8S_IMAGE', image)}"`,
    `BASE_IMAGE="${shDefault('APPLIK8S_BASE_IMAGE', baseImage)}"`,
    `FIELD_MANAGER="${shDefault('APPLIK8S_FIELD_MANAGER', 'applik8s-standalone')}"`,
    `DEPLOYMENT=${JSON.stringify(manifest.metadata.name)}`,
    `NAMESPACE=${JSON.stringify(namespace)}`,
    '',
    `if [ "${shDefault('APPLIK8S_BUILD_BASE', '0')}" = "1" ]; then`,
    `  BASE_DOCKERFILE="${shDefault('APPLIK8S_BASE_DOCKERFILE', 'Dockerfile.operator-host')}"`,
    `  BASE_CONTEXT="${shDefault('APPLIK8S_BASE_CONTEXT', '.')}"`,
    '  "$DOCKER" build --file "$BASE_DOCKERFILE" --tag "$BASE_IMAGE" "$BASE_CONTEXT"',
    'fi',
    '',
    `"$DOCKER" build --build-arg "APPLIK8S_BASE_IMAGE=$BASE_IMAGE" --file "$SCRIPT_DIR/${container.build.dockerfile}" --tag "$IMAGE" "$SCRIPT_DIR"`,
    `if [ "${shDefault('APPLIK8S_PUSH_IMAGE', '0')}" = "1" ]; then`,
    '  "$DOCKER" push "$IMAGE"',
    'fi',
    '',
    'for manifest in "$SCRIPT_DIR"/kubernetes/*.yaml; do',
    '  "$KUBECTL" apply --server-side --field-manager="$FIELD_MANAGER" --filename "$manifest"',
    'done',
    '',
    'if [ "$IMAGE" != "$DEFAULT_IMAGE" ]; then',
    '  if [ -n "$NAMESPACE" ]; then',
    '    "$KUBECTL" set image "deployment/$DEPLOYMENT" "operator-host=$IMAGE" --namespace "$NAMESPACE"',
    '  else',
    '    "$KUBECTL" set image "deployment/$DEPLOYMENT" "operator-host=$IMAGE"',
    '  fi',
    'fi',
    '',
  ].join('\n');
}

export function emitTypeKroApplyScript(resources: readonly TypeKroCompositionResource[]): string {
  const shDefault = (name: string, fallback: string) => ['$', `{${name}:-${fallback}}`].join('');
  const schemaApiResourceWaits = typeKroSchemaApiResources(resources).map((resource) => `wait_for_api_resource ${shellQuote(resource.group)} ${shellQuote(resource.kind)}`);
  return [
    '#!/usr/bin/env sh',
    'set -eu',
    '',
    'SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"',
    `KUBECTL="${shDefault('KUBECTL', 'kubectl')}"`,
    `KUBE_CONTEXT="${shDefault('APPLIK8S_KUBE_CONTEXT', '')}"`,
    `FIELD_MANAGER="${shDefault('APPLIK8S_FIELD_MANAGER', 'applik8s-typekro')}"`,
    `FORCE_RGD_NAME="${shDefault('APPLIK8S_FORCE_RGD_NAME', '')}"`,
    `WAIT_TIMEOUT="${shDefault('APPLIK8S_WAIT_TIMEOUT', '180s')}"`,
    `APPLY_RETRY_SECONDS="${shDefault('APPLIK8S_APPLY_RETRY_SECONDS', '180')}"`,
    'RESOURCES_DIR="$SCRIPT_DIR/resources"',
    'INSTANCES_DIR="$SCRIPT_DIR/instances"',
    'TEMPLATE_MANIFESTS="$SCRIPT_DIR/template-manifests.txt"',
    '',
    'if [ ! -d "$RESOURCES_DIR" ]; then',
    '  echo "TypeKro resources directory not found: $RESOURCES_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    ...typeKroKubectlContextShell(),
    'is_kind() {',
    '  grep -Eq "^kind:[[:space:]]*$2[[:space:]]*$" "$1"',
    '}',
    '',
    'has_typekro_expression() {',
    '  grep -Eq "^[[:space:]]*_type:[[:space:]]*" "$1" && grep -Eq "^[[:space:]]*expression:[[:space:]]*" "$1"',
    '}',
    '',
    'is_typekro_template_manifest() {',
    '  [ -f "$TEMPLATE_MANIFESTS" ] && grep -Fxq "$(basename "$1")" "$TEMPLATE_MANIFESTS"',
    '}',
    '',
    'apply_manifest() {',
    '  if [ -n "$FORCE_RGD_NAME" ] && is_kind "$1" ResourceGraphDefinition && grep -Fxq "  name: $FORCE_RGD_NAME" "$1"; then',
    '    echo "Completing scoped provider-migration ownership handoff for ResourceGraphDefinition/$FORCE_RGD_NAME"',
    '    kubectl_run apply --server-side --force-conflicts --field-manager="$FIELD_MANAGER" --filename "$1"',
    '    return',
    '  fi',
    '  kubectl_run apply --server-side --field-manager="$FIELD_MANAGER" --filename "$1"',
    '}',
    '',
    'apply_with_retry() {',
    '  deadline=$(( $(date +%s) + APPLY_RETRY_SECONDS ))',
    '  while :; do',
    '    if apply_manifest "$1"; then',
    '      if deletion_timestamp=$(kubectl_run get --filename "$1" --output=jsonpath="{.metadata.deletionTimestamp}" 2>/dev/null); then',
    '        if [ -z "$deletion_timestamp" ]; then',
    '          return 0',
    '        fi',
    '        echo "Waiting for terminating resource from $1 to disappear before recreating it..." >&2',
    '      fi',
    '    fi',
    '    if [ "$(date +%s)" -ge "$deadline" ]; then',
    '      echo "Timed out applying $1 after $APPLY_RETRY_SECONDS seconds" >&2',
    '      return 1',
    '    fi',
    '    sleep 2',
    '  done',
    '}',
    '',
    'wait_for_api_resource() {',
    '  group="$1"',
    '  kind="$2"',
    '  deadline=$(( $(date +%s) + APPLY_RETRY_SECONDS ))',
    '  until kubectl_run api-resources --api-group="$group" --no-headers 2>/dev/null | grep -Eq "[[:space:]]$kind$"; do',
    '    if [ "$(date +%s)" -ge "$deadline" ]; then',
    '      echo "Timed out waiting for TypeKro API resource $kind in group $group after $APPLY_RETRY_SECONDS seconds" >&2',
    '      return 1',
    '    fi',
    '    sleep 2',
    '  done',
    '}',
    '',
    'wait_for_resource_graph_definition() {',
    '  manifest="$1"',
    '  name=$(kubectl_run get --filename "$manifest" --output=jsonpath="{.metadata.name}")',
    '  deadline=$(( $(date +%s) + APPLY_RETRY_SECONDS ))',
    '  while :; do',
    '    generation=$(kubectl_run get resourcegraphdefinition.kro.run "$name" --output=jsonpath="{.metadata.generation}" 2>/dev/null || true)',
    "    accepted=$(kubectl_run get resourcegraphdefinition.kro.run \"$name\" --output=jsonpath='{range .status.conditions[?(@.type==\"GraphAccepted\")]}{.status}:{.observedGeneration}:{.reason}:{.message}{\"\\n\"}{end}' 2>/dev/null || true)",
    "    ready=$(kubectl_run get resourcegraphdefinition.kro.run \"$name\" --output=jsonpath='{range .status.conditions[?(@.type==\"Ready\")]}{.status}:{.observedGeneration}:{.reason}:{.message}{\"\\n\"}{end}' 2>/dev/null || true)",
    '    case "$accepted" in',
    '      "False:$generation:"*)',
    '        echo "ResourceGraphDefinition/$name rejected generation $generation: $accepted" >&2',
    '        return 1',
    '        ;;',
    '    esac',
    '    case "$accepted|$ready" in',
    '      "True:$generation:"*"|True:$generation:"*) return 0 ;;',
    '    esac',
    '    if [ "$(date +%s)" -ge "$deadline" ]; then',
    '      echo "Timed out waiting for ResourceGraphDefinition/$name generation $generation; GraphAccepted=$accepted Ready=$ready" >&2',
    '      return 1',
    '    fi',
    '    sleep 2',
    '  done',
    '}',
    '',
    'has_resources=0',
    'for manifest in "$RESOURCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  has_resources=1',
    'done',
    'if [ "$has_resources" = "0" ]; then',
    '  echo "No TypeKro resource YAML files found under $RESOURCES_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    'echo "Applying TypeKro prerequisite CustomResourceDefinitions..."',
    'for manifest in "$RESOURCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  if is_kind "$manifest" CustomResourceDefinition; then',
    '    apply_manifest "$manifest"',
    '    kubectl_run wait --for=condition=Established --timeout="$WAIT_TIMEOUT" --filename "$manifest"',
    '  fi',
    'done',
    '',
    'echo "Applying TypeKro ResourceGraphDefinitions..."',
    'for manifest in "$RESOURCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  if is_kind "$manifest" ResourceGraphDefinition; then',
    '    apply_manifest "$manifest"',
    '  fi',
    'done',
    '',
    'echo "Waiting for current TypeKro ResourceGraphDefinition generations..."',
    'for manifest in "$RESOURCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  if is_kind "$manifest" ResourceGraphDefinition; then',
    '    wait_for_resource_graph_definition "$manifest"',
    '  fi',
    'done',
    ...(schemaApiResourceWaits.length > 0 ? [
      '',
      'echo "Waiting for TypeKro stack APIs..."',
      ...schemaApiResourceWaits,
    ] : []),
    '',
    'echo "Applying remaining TypeKro resources..."',
    'for manifest in "$RESOURCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  if is_kind "$manifest" CustomResourceDefinition || is_kind "$manifest" ResourceGraphDefinition; then',
    '    continue',
    '  fi',
    '  if is_typekro_template_manifest "$manifest"; then',
    '    echo "Skipping TypeKro template resource owned by a ResourceGraphDefinition: $manifest"',
    '    continue',
    '  fi',
    '  if has_typekro_expression "$manifest"; then',
    '    echo "Skipping TypeKro template resource with expression placeholders: $manifest"',
    '    continue',
    '  fi',
    '  apply_with_retry "$manifest"',
    'done',
    '',
    'echo "Applying TypeKro stack instances..."',
    'for manifest in "$INSTANCES_DIR"/*.yaml; do',
    '  [ -e "$manifest" ] || continue',
    '  apply_with_retry "$manifest"',
    'done',
    '',
    'echo "Applied TypeKro composition resources from $RESOURCES_DIR"',
    '',
  ].join('\n');
}
