import { describeCharacterSuite, type CharacterScenario } from '../../testing/test/character.js';

const s = (name: string, userStory: string, arrange: readonly string[], act: readonly string[], assert: readonly string[]): CharacterScenario => ({ name, userStory, arrange, act, assert });

describeCharacterSuite('runtime character tests', [
  s('starts from manifest, ABI, artifact, and runtime config', 'As an operator runtime, I start from a compiled bundle contract.', ['Create RuntimeStartOptions with manifest, config, ABI, artifact path, and wasm adapter.'], ['Call controller.start(options).'], ['Runtime state reports started, watched resources, leader state, queue depth, and in-flight reconciles.']),
  s('rejects incompatible runtime or handler ABI before invocation', 'As a cluster admin, I want unsafe bundles to fail closed.', ['Create a manifest requiring unsupported runtime or ABI.'], ['Start the runtime.'], ['Start fails with RUNTIME_INCOMPATIBLE or ABI_INCOMPATIBLE and no handlers run.']),
  s('invokes the correct handler export', 'As a controller, I route watch events to the right user logic.', ['Manifest maps ImageJob reconcile to handler export image-job-reconcile-0.'], ['Invoke with a HandlerInput for ImageJob.'], ['The WASM component export is called and HandlerInvocationResult includes normalized plan, logs, and duration.']),
  s('validates handler input and output', 'As a runtime, I protect Kubernetes from invalid handler data.', ['Prepare invalid handler input or invalid handler output.'], ['Invoke with validation enabled.'], ['Invocation fails before apply with HANDLER_OUTPUT_INVALID or schema diagnostics.']),
  s('reports traps, timeouts, and cancellation', 'As an operator user, I see handler execution failures clearly.', ['Handlers throw, run past timeout, or receive cancellation.'], ['Invoke through HandlerInvoker.'], ['Failures are HANDLER_TRAP, HANDLER_TIMEOUT, or cancellation diagnostics with object and handler context.']),
  s('applies server-side apply operations', 'As a reconciler, I apply desired resources through Kubernetes semantics.', ['Normalized plan contains apply operations with field manager and owner.'], ['OperationApplier.apply(plan, context).'], ['Kubernetes apply is called with field ownership and valid owner refs.']),
  s('patches status through status subresource', 'As a CRD author, I preserve Kubernetes status semantics.', ['Normalized plan contains status operation for an object with status subresource.'], ['Apply the plan.'], ['Runtime patches /status and records statusPatched true.']),
  s('records events, finalizers, deletes, patches, and requeues', 'As a handler author, all operation-plan entries are runtime mediated.', ['Plan includes event, finalizer, delete, patch, and requeue operations.'], ['Apply the plan.'], ['ApplyResult reports applied operations, eventsRecorded, and requeueAfterSeconds.']),
  s('reports partial apply failures', 'As an operator user, I see which effects succeeded and which failed.', ['Plan has several operations and one Kubernetes API call fails.'], ['Apply the plan.'], ['ApplyResult separates appliedOperations from failedOperations and schedules retry when configured.']),
  s('surfaces RBAC denial as permission failure', 'As a cluster admin, I can fix generated or configured RBAC.', ['Runtime lacks permission for a status patch or apply.'], ['Apply the plan.'], ['Failure is RBAC_DENIED with operation kind and object ref.']),
  s('treats conflicts and stale reads as retryable controller behavior', 'As a Kubernetes operator, I handle normal API races safely.', ['Kubernetes returns conflict on apply or status patch.'], ['Apply the plan.'], ['Runtime reports conflict and retry/requeue without corrupting status.']),
  s('implements event semantics without exactly-once claims', 'As an app developer, I understand Kubernetes watch behavior.', ['Observe ADDED, MODIFIED, DELETED, deletionTimestamp, and status changes.'], ['Runtime routes created, updated, deleted, finalize, and statusChanged handlers.'], ['Handlers run as reconcile predicates and never claim exactly-once or global ordering.']),
  s('captures replay records', 'As a developer, I debug reconciles locally.', ['Invoke a handler and apply its plan.'], ['ReplayRecorder.capture(record).'], ['Record includes input, result, normalized plan, logs, metrics, applied operations, and failed operations.']),
  s('replays without live effects', 'As a developer, I reproduce behavior safely.', ['Load a replay record.'], ['Replay through a HandlerInvoker.'], ['HandlerInvocationResult is produced without Kubernetes mutation.']),
  s('reports health and metrics consistently', 'As an operator user, I can observe generated operators.', ['Runtime has reconciles, failures, queue depth, and apply operations.'], ['Call controller.health() and controller.metrics().'], ['Health and metrics include runtime status, reconcile counts, durations, retries, queue depth, traps, and status patch failures.']),
]);
