import type { EffectExecutionMode, HandlerApiStyle, HandlerEventType, HandlerId, JsonObject, JsonPrimitive, KubernetesName, NamespaceName, ObjectMeta, ObjectRef, ReconcileId, Result, SourceLocation } from './common.js';
import type { CapabilityClientSet } from './capability.js';
import type { AnyKubernetesObject, AnyResourceDefinition, PermissionRule, ResourceDefinition, ResourceObject } from './resource.js';
import type { ApplyOwnership, DeleteOptions, EventOperation, HandlerResult, JsonPatch, NormalizedOperationPlan, OperationPlanInput, PartialStatus, PatchOperation, RequeueOperation, RequeuePolicy, StatusOperation } from './operation-plan.js';

export type MaybePromise<T> = T | Promise<T>;
export type DraftValue<T> = T extends JsonPrimitive ? T : T extends ReadonlyArray<infer U> ? DraftValue<U>[] : T extends object ? { -readonly [K in keyof T]: DraftValue<T[K]> } : T;
export type StatusDraft<TStatus extends object> = { -readonly [K in keyof TStatus]?: DraftValue<TStatus[K]> };
export type Handler<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> = (object: ResourceObject<TSpec, TStatus>, context: HandlerContext<TSpec, TStatus, TCapabilities>) => MaybePromise<Result<HandlerResult<TStatus>>>;
// biome-ignore lint/suspicious/noConfusingVoidType: async proxy handlers with no explicit return infer Promise<void>.
export type ProxyHandlerReturn<TStatus extends object> = void | HandlerResult<TStatus> | Result<HandlerResult<TStatus>>;
export type ProxyHandler<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> = (scope: HandlerProxyScope<TSpec, TStatus, TCapabilities>) => MaybePromise<ProxyHandlerReturn<TStatus>>;
export interface ResourceEventSources<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly context: ContextResourceEventSources<TSpec, TStatus, TCapabilities>; reconcile(handler: ProxyHandler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; created(handler: ProxyHandler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; updated(handler: ProxyHandler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; deleted(handler: ProxyHandler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; finalize(handler: ProxyHandler<TSpec, TStatus, TCapabilities>, options?: FinalizeHandlerOptions): HandlerRegistration<TSpec, TStatus, TCapabilities>; statusChanged(handler: ProxyHandler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; }
export interface ContextResourceEventSources<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { reconcile(handler: Handler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; created(handler: Handler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; updated(handler: Handler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; deleted(handler: Handler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; finalize(handler: Handler<TSpec, TStatus, TCapabilities>, options?: FinalizeHandlerOptions): HandlerRegistration<TSpec, TStatus, TCapabilities>; statusChanged(handler: Handler<TSpec, TStatus, TCapabilities>): HandlerRegistration<TSpec, TStatus, TCapabilities>; }
export interface FinalizeHandlerOptions { readonly finalizer?: string; readonly finalizers?: readonly string[]; }
export interface HandlerRegistration<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly id: HandlerId; readonly event: HandlerEventType; readonly resource: ResourceDefinition<TSpec, TStatus, TCapabilities>; readonly handlerStyle?: HandlerApiStyle; readonly sourceLocation?: SourceLocation; readonly finalizers?: readonly string[]; }
export interface HandlerRegistrationSummary { readonly id: HandlerId; readonly event: HandlerEventType; readonly handlerStyle?: HandlerApiStyle; readonly sourceLocation?: SourceLocation; readonly finalizers?: readonly string[]; }
export type AnyHandlerRegistration = HandlerRegistrationSummary;
export type HandlerRegistrationForResource<TResource extends AnyResourceDefinition<TCapabilities>, TCapabilities extends CapabilityClientSet> = TResource extends ResourceDefinition<infer TSpec, infer TStatus, infer TResourceCapabilities> ? HandlerRegistration<TSpec, TStatus, TResourceCapabilities & TCapabilities> : AnyHandlerRegistration;
export type HandlerRegistrationForResources<TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>, TCapabilities extends CapabilityClientSet> = { readonly [K in keyof TResources]: HandlerRegistrationForResource<TResources[K], TCapabilities> }[keyof TResources];

export interface HandlerContext<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly object: ResourceObject<TSpec, TStatus>; readonly event: HandlerEventType; readonly reconcileId: ReconcileId; readonly capabilities: TCapabilities; readonly names: NameHelpers; readonly k8s: KubernetesFactoryGroup; readonly batch: KubernetesFactoryGroup; apply(plan: OperationPlanInput<TStatus>): Result<HandlerResult<TStatus>>; apply<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: ApplyTargetOptions): Result<HandlerResult<TStatus>>; apply<TTarget extends OperationTarget<TStatus>>(targets: readonly TTarget[], plan?: OperationPlanInput<TStatus>): Result<HandlerResult<TStatus>>; applyGraph<TGraph extends object, TGraphSpec extends object = object>(application: GraphApplication<TGraph, TStatus, TGraphSpec>): Result<HandlerResult<TStatus>>; plan<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: ApplyTargetOptions): Result<NormalizedOperationPlan<TStatus>>; status(status: PartialStatus<TStatus>): StatusOperation<TStatus>; status<TTargetSpec extends object, TTargetStatus extends object>(resource: ResourceDefinition<TTargetSpec, TTargetStatus>, name: KubernetesName, status: PartialStatus<TTargetStatus>, namespace?: NamespaceName): StatusOperation<TTargetStatus>; patch(ref: ObjectRef, patch: JsonPatch): PatchOperation; delete(ref: ObjectRef, options?: DeleteOptions): import('./operation-plan.js').DeleteOperation; delete(resource: AnyKubernetesObject, options?: DeleteOptions): import('./operation-plan.js').DeleteOperation; delete<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: DeleteTargetOptions): Result<HandlerResult<TStatus>>; delete<TTarget extends OperationTarget<TStatus>>(targets: readonly TTarget[], plan?: OperationPlanInput<TStatus>): Result<HandlerResult<TStatus>>; recordEvent(event: EventOperation): EventOperation; requeue(policy: RequeuePolicy): RequeueOperation; noop(): Result<HandlerResult<TStatus>>; }
export interface HandlerProxyScope<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly object: ResourceObject<TSpec, TStatus>; readonly spec: TSpec; readonly metadata: ObjectMeta; readonly event: HandlerEventType; readonly reconcileId: ReconcileId; readonly capabilities: TCapabilities; readonly names: NameHelpers; readonly k8s: KubernetesFactoryGroup; readonly batch: KubernetesFactoryGroup; readonly status: StatusDraft<TStatus>; readonly resources: HandlerResourceDraft<TStatus>; readonly events: HandlerEventDraft; readonly finalizers: HandlerFinalizerDraft; apply(plan: OperationPlanInput<TStatus>): void; apply<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: ApplyTargetOptions): void; apply<TTarget extends OperationTarget<TStatus>>(targets: readonly TTarget[], plan?: OperationPlanInput<TStatus>): void; applyGraph<TGraph extends object, TGraphSpec extends object = object>(application: GraphApplication<TGraph, TStatus, TGraphSpec>): void; delete(ref: ObjectRef, options?: DeleteOptions): void; delete(resource: AnyKubernetesObject, options?: DeleteOptions): void; delete<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: DeleteTargetOptions): void; delete<TTarget extends OperationTarget<TStatus>>(targets: readonly TTarget[], plan?: OperationPlanInput<TStatus>): void; patch(ref: ObjectRef, patch: JsonPatch): void; setStatus<TTargetSpec extends object, TTargetStatus extends object>(resource: ResourceDefinition<TTargetSpec, TTargetStatus>, name: KubernetesName, status: PartialStatus<TTargetStatus>, namespace?: NamespaceName): void; recordEvent(event: EventOperation): void; requeue(policy: RequeuePolicy): void; plan<TTarget extends OperationTarget<TStatus>>(target: TTarget, options?: ApplyTargetOptions): Result<NormalizedOperationPlan<TStatus>>; }
export interface HandlerResourceDraft<TStatus extends object = JsonObject> { apply(resource: AnyKubernetesObject, options?: ApplyTargetOptions): void; applyTarget(target: OperationTarget<TStatus> | ApplyTargetInput<TStatus>): void; delete(ref: ObjectRef, options?: DeleteOptions): void; deleteTarget(target: OperationTarget<TStatus> | DeleteTargetInput<TStatus>): void; patch(ref: ObjectRef, patch: JsonPatch): void; }
export interface HandlerEventDraft { record(event: EventOperation): void; normal(reason: string, message: string, regarding?: ObjectRef): void; warning(reason: string, message: string, regarding?: ObjectRef): void; }
export interface HandlerFinalizerDraft { add(finalizer: string): void; remove(finalizer: string): void; }
export interface GraphApplication<TGraph extends object = object, TStatus extends object = JsonObject, TGraphSpec extends object = object> { readonly graph: TGraph; readonly spec: TGraphSpec; readonly adapter: GraphAdapter<TGraph, TStatus, TGraphSpec>; }
export interface GraphAdapter<TGraph extends object = object, TStatus extends object = JsonObject, TGraphSpec extends object = object> { render(graph: TGraph, spec: TGraphSpec): Result<NormalizedOperationPlan<TStatus>>; inferRbac(graph: TGraph): Result<readonly PermissionRule[]>; renderStatus(graph: TGraph, spec: TGraphSpec): Result<PartialStatus<TStatus>>; }
export interface ApplyTargetOptions { readonly fieldManager?: string; readonly force?: boolean; readonly owner?: ObjectRef; readonly ownership?: ApplyOwnership; }
export interface DeleteTargetOptions extends DeleteOptions { readonly owner?: ObjectRef; }
export interface ApplyTargetInput<TStatus extends object = object> { readonly target: OperationTarget<TStatus>; readonly options?: ApplyTargetOptions; }
export interface DeleteTargetInput<TStatus extends object = object> { readonly target: OperationTarget<TStatus>; readonly options?: DeleteTargetOptions; }
export interface OperationTarget<TStatus extends object = object> { readonly targetKind: 'operationTarget'; readonly adapter: OperationTargetAdapter<this, TStatus>; }
export interface OperationTargetAdapter<TTarget extends OperationTarget<TStatus>, TStatus extends object = object> { renderApply(target: TTarget, options?: ApplyTargetOptions): Result<NormalizedOperationPlan<TStatus>>; renderDelete(target: TTarget, options?: DeleteTargetOptions): Result<NormalizedOperationPlan<TStatus>>; inferRbac(target: TTarget): Result<readonly PermissionRule[]>; }
export interface EffectPolicy { readonly mode: EffectExecutionMode; readonly reason?: string; readonly replayable: boolean; }
export interface NameHelpers { dnsSafe(input: string, options?: NameOptions): KubernetesName; withHash(prefix: string, input: string, options?: NameOptions): KubernetesName; }
export interface NameOptions { readonly maxLength?: number; readonly collisionSuffixLength?: number; }
export interface KubernetesFactoryGroup { Job(config: KubernetesFactoryConfig): import('./resource.js').KubernetesObject<JsonObject, JsonObject>; Deployment(config: KubernetesFactoryConfig): import('./resource.js').KubernetesObject<JsonObject, JsonObject>; Service(config: KubernetesFactoryConfig): import('./resource.js').KubernetesObject<JsonObject, JsonObject>; ConfigMap(config: ConfigMapFactoryConfig): import('./resource.js').KubernetesObject<JsonObject, JsonObject> & { readonly data?: Readonly<Record<string, string>>; readonly binaryData?: Readonly<Record<string, string>>; readonly immutable?: boolean; }; StatefulSet(config: KubernetesFactoryConfig): import('./resource.js').KubernetesObject<JsonObject, JsonObject>; }
export interface KubernetesFactoryConfig extends KubernetesFactoryBaseConfig { readonly image?: string; readonly env?: Readonly<Record<string, string>>; readonly spec?: JsonObject; }
export interface ConfigMapFactoryConfig extends KubernetesFactoryBaseConfig { readonly data?: Readonly<Record<string, string>>; readonly binaryData?: Readonly<Record<string, string>>; readonly immutable?: boolean; }
export interface KubernetesFactoryBaseConfig { readonly name: KubernetesName; readonly namespace?: NamespaceName; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
