import type { ConversionStrategy, HandlerAbiVersion, HandlerEventType, HandlerTrustLevel, Kind, KubernetesName, NamespaceName, OperatorManifestVersion, OperatorName, PluralName, ResourceScope, Result, SemverRange, Sha256Digest, SignatureAlgorithm, StatusConvention, Timestamp } from './common.js';
import type { CapabilityClientSet, CapabilityDescriptor, CapabilityExecutionPolicy } from './capability.js';
import type { EffectPolicy, HandlerRegistrationForResources } from './handler.js';
import type { AnyResourceDefinition, DeleteResult, PermissionRule } from './resource.js';
import type { DomainDataPolicy } from './lifecycle.js';
import type { RuntimeAdapterRequirement, RuntimeConfig } from './runtime.js';
import type { RuntimePayloadSchemaDigests } from './schema.js';
import type { ContainerRecipe } from '@applik8s/typetainer';

export interface OperatorDefinition<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>> { readonly name: OperatorName; readonly resources: TResources; readonly handlers: readonly HandlerRegistrationForResources<TResources, TCapabilities>[]; readonly capabilities?: Readonly<Record<keyof TCapabilities & string, CapabilityDescriptor>>; readonly permissions?: readonly PermissionRule[]; readonly deployment?: OperatorDeploymentOptions; readonly runtime?: RuntimeConfig; readonly trustLevel: HandlerTrustLevel; readonly effects?: EffectPolicy; readonly lifecycle?: OperatorLifecycleContract; }
export interface OperatorDeploymentOptions { readonly namespace?: NamespaceName; readonly replicas?: number; readonly scope?: ResourceScope; readonly serviceAccountName?: KubernetesName; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
export interface OperatorManifest { readonly apiVersion: OperatorManifestVersion; readonly kind: 'OperatorBundle'; readonly metadata: OperatorManifestMetadata; readonly spec: OperatorManifestSpec; }
export interface OperatorManifestMetadata { readonly name: OperatorName; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
export interface OperatorManifestSpec { readonly handlerAbi: HandlerAbiVersion; readonly payloadSchemaDigests: RuntimePayloadSchemaDigests; readonly requiresRuntime: SemverRange; readonly handlerArtifact: HandlerArtifact; readonly adapterRequirements?: RuntimeAdapterRequirement; readonly handlerExports: readonly HandlerExport[]; readonly ownedCrds: readonly OwnedCrd[]; readonly watches: readonly WatchRegistration[]; readonly permissions: readonly PermissionRule[]; readonly capabilities?: Readonly<Record<string, CapabilityDescriptor>>; readonly security: OperatorSecurityContract; readonly lifecycle: OperatorLifecycleContract; readonly runtime?: RuntimeConfig; readonly container?: ContainerRecipe; readonly bundle: BundleMetadata; }
export interface HandlerArtifact { readonly kind: 'wasm-component'; readonly path: string; readonly digest: Sha256Digest; }
export interface HandlerExport { readonly handlerId: import('./common.js').HandlerId; readonly exportName: string; readonly resource: ResourceTypeRef; readonly event: HandlerEventType; readonly finalizers?: readonly string[]; }
export interface ResourceTypeRef { readonly apiVersion: import('./common.js').ApiVersion; readonly kind: Kind; }
export interface OwnedCrd { readonly apiVersion: import('./common.js').ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly versions: readonly string[]; readonly storageVersion: string; readonly conversionStrategy: ConversionStrategy; readonly versioning: CrdVersioningPosture; readonly statusSubresource: boolean; readonly statusConvention?: StatusConvention; }
export interface CrdVersioningPosture { readonly multiVersion: 'unsupported' | 'singleVersion'; readonly conversionWebhook: 'unsupported' | 'notConfigured'; readonly storageMigration: 'notRequired' | 'unsupported'; readonly rollbackSafety: 'schemaCompatibleOnly'; }
export interface WatchRegistration { readonly apiVersion: import('./common.js').ApiVersion; readonly kind: Kind; readonly namespace?: NamespaceName; readonly events: readonly HandlerEventType[]; readonly handlers: readonly import('./common.js').HandlerId[]; }
export interface BundleMetadata { readonly digest: Sha256Digest; readonly sourceDigest: Sha256Digest; readonly compilerVersion: string; readonly createdAt: Timestamp; readonly artifacts: readonly BundleArtifact[]; readonly supplyChain: SupplyChainMetadata; readonly portability?: PortabilityMetadata; }
export interface BundleArtifact { readonly kind: BundleArtifactKind; readonly path: string; readonly digest: Sha256Digest; }
export type BundleArtifactKind = 'wasm-component' | 'runtime-contract' | 'handler-wit' | 'javascript-bundle' | 'javascript-source-map' | 'esbuild-metafile' | 'kubernetes-yaml' | 'operator-manifest';
export interface SupplyChainMetadata { readonly signatures: readonly ArtifactSignature[]; readonly sbomDigest?: Sha256Digest; readonly provenanceDigest?: Sha256Digest; readonly posture?: SupplyChainPosture; }
export interface SupplyChainPosture { readonly signing: 'unsigned' | 'signed'; readonly sbom: 'notGenerated' | 'digestRecorded'; readonly provenance: 'notGenerated' | 'digestRecorded'; readonly admission: 'metadataOnly' | 'verifiable'; }
export interface ArtifactSignature { readonly algorithm: SignatureAlgorithm; readonly digest: Sha256Digest; readonly identity?: string; }
export interface PortabilityMetadata { readonly operatorIdentity: string; readonly bundleDigest: Sha256Digest; readonly runtimeAbi: HandlerAbiVersion; readonly crdVersions: readonly string[]; readonly labels: Readonly<Record<string, string>>; }
export interface OperatorSecurityContract { readonly trustLevel: HandlerTrustLevel; readonly effects: EffectPolicy; readonly capabilities: readonly CapabilityRequirement[]; readonly rbac: RbacContract; readonly secrets: SecretHandlingContract; readonly hostAccess: HostAccessContract; readonly portability: PortabilitySecurityContract; }
export interface CapabilityRequirement { readonly name: string; readonly descriptor: CapabilityDescriptor; readonly required: boolean; readonly exposedToHandlers: boolean; readonly execution: CapabilityExecutionPolicy; readonly rbac?: readonly PermissionRule[]; }
export interface RbacContract { readonly mode: 'explicit' | 'inferred' | 'explicitAndInferred'; readonly rules: readonly PermissionRule[]; readonly leastPrivilegeReviewed: boolean; }
export interface SecretHandlingContract { readonly mode: 'referencesOnly'; readonly secretRefs: readonly import('./capability.js').SecretRef[]; readonly embedSecretMaterial: false; }
export interface HostAccessContract { readonly filesystem: 'denied' | 'declaredCapabilityOnly' | 'allowedByPolicy'; readonly network: 'denied' | 'declaredCapabilityOnly' | 'allowedByPolicy'; readonly environment: 'denied' | 'declaredConfigOnly' | 'allowedByPolicy'; readonly undeclaredHostImports: 'denied'; }
export interface PortabilitySecurityContract { readonly enforcement: 'failClosed'; readonly deterministicBuild: boolean; readonly environmentAccess: 'denied' | 'allowedByPolicy'; readonly filesystemAccess: 'denied' | 'allowedByPolicy'; readonly networkAccess: 'denied' | 'allowedByPolicy'; readonly dynamicImport: 'denied' | 'allowedByPolicy'; readonly localCredentialPaths: 'denied'; readonly embeddedSecretMaterial: 'denied'; readonly unsupportedNativeModules: 'denied'; readonly sourceMaps: SourceMapSecurityContract; }
export interface SourceMapSecurityContract { readonly emitted: boolean; readonly sourceContent: 'excluded' | 'includedByPolicy'; readonly paths: 'redacted' | 'preservedByPolicy'; }
export interface OperatorLifecycleContract { readonly install: LifecycleActionContract; readonly upgrade: LifecycleCompatibilityContract; readonly rollback: LifecycleCompatibilityContract; readonly uninstallController: LifecycleActionContract; readonly deleteDomainData: LifecycleActionContract; }
export interface LifecycleActionContract { readonly action: import('./common.js').LifecycleAction; readonly domainDataPolicy: DomainDataPolicy; readonly requiresExplicitConfirmation: boolean; }
export interface LifecycleCompatibilityContract { readonly requiresRuntimeCompatibility: boolean; readonly requiresHandlerAbiCompatibility: boolean; readonly requiresCrdVersionCompatibility: boolean; readonly requiresStorageVersionCompatibility: boolean; readonly requiresExternalEffectCompatibility: boolean; }
export interface OperatorBundleRepository { create(bundle: OperatorManifest): Promise<Result<OperatorManifest>>; read(name: OperatorName): Promise<Result<OperatorManifest>>; list(): Promise<Result<readonly OperatorManifest[]>>; update(bundle: OperatorManifest): Promise<Result<OperatorManifest>>; delete(name: OperatorName): Promise<Result<DeleteResult>>; }
