import type { CapabilityClientSet, SecretRef } from './capability.js';
import type { ApiVersion, HandlerEventType, Kind, KubernetesName, NamespaceName, ObjectMeta, ObjectRef, PluralName, ResourceScope, Result, WatchEventType } from './common.js';
import type { ResourceEventSources } from './handler.js';
import type { DeleteOptions, JsonPatch, PartialStatus } from './operation-plan.js';
import type { AnyRuntimeSchema, RuntimeSchema } from './schema.js';

export interface KubernetesObject<TSpec extends object = import('./common.js').JsonObject, TStatus extends object = import('./common.js').JsonObject> { readonly apiVersion: ApiVersion; readonly kind: Kind; readonly metadata: ObjectMeta; readonly spec?: TSpec; readonly status?: TStatus; readonly [key: string]: unknown; }
export type AnyKubernetesObject = KubernetesObject<object, object>;
export type ResourceObject<TSpec extends object, TStatus extends object> = KubernetesObject<TSpec, TStatus> & { readonly spec: TSpec; };
export type ResourceOwnership = 'owned' | 'external';
export type KubernetesReadAccess = 'local' | 'connection' | 'both';
export interface KubernetesReadResourceDefinition<TSpec extends object = object, TStatus extends object = object> { readonly apiVersion: ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly namespaces?: readonly NamespaceName[] | 'all'; readonly access: KubernetesReadAccess; readonly permissions: Pick<ResourcePermissionFactory, 'read'>; readonly __specType?: TSpec; readonly __statusType?: TStatus; }
export type AnyKubernetesReadResourceDefinition = KubernetesReadResourceDefinition<object, object>;
export interface ResourceDefinition<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { (input: ResourceInstanceInput<TSpec>): ResourceObject<TSpec, TStatus>; readonly apiVersion: ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly spec: RuntimeSchema<TSpec>; readonly status?: RuntimeSchema<TStatus>; readonly statusConvention?: import('./common.js').StatusConvention; readonly statusSubresource: boolean; readonly additionalPrinterColumns?: readonly PrinterColumn[]; readonly versions: readonly ResourceVersionDefinition<TSpec, TStatus>[]; readonly permissions: ResourcePermissionFactory; readonly on: ResourceEventSources<TSpec, TStatus, TCapabilities>; readonly resourceOwnership?: ResourceOwnership; instance(input: ResourceInstanceInput<TSpec>): ResourceObject<TSpec, TStatus>; index(name: string, options: ResourceIndexOptions): ResourceIndex<TSpec, TStatus>; create(input: ResourceInstanceInput<TSpec> | ResourceObject<TSpec, TStatus>): Promise<ResourceObject<TSpec, TStatus>>; get(query: ResourceGetQuery): Promise<ResourceObject<TSpec, TStatus> | undefined>; query(query?: ResourceReadQuery): Promise<ResourceReadList<TSpec, TStatus>>; patch(query: ResourceGetQuery, patch: JsonPatch): Promise<ResourceObject<TSpec, TStatus>>; delete(query: ResourceGetQuery, options?: DeleteOptions): Promise<DeleteResult>; increment(input: ResourceCounterIncrementInput<TSpec>): Promise<ResourceCounterIncrementResult>; }
export interface AnyResourceVersionDefinition { readonly name: string; readonly served: boolean; readonly storage: boolean; readonly spec: AnyRuntimeSchema; readonly status?: AnyRuntimeSchema; readonly compatibility: VersionCompatibility; }
export interface AnyResourceDefinition<TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly apiVersion: ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly spec: AnyRuntimeSchema; readonly status?: AnyRuntimeSchema; readonly statusConvention?: import('./common.js').StatusConvention; readonly statusSubresource: boolean; readonly additionalPrinterColumns?: readonly PrinterColumn[]; readonly versions: readonly AnyResourceVersionDefinition[]; readonly permissions: ResourcePermissionFactory; readonly capabilityNames?: readonly (keyof TCapabilities & string)[]; readonly eventMetadata?: readonly AnyResourceEventMetadata[]; readonly resourceOwnership?: ResourceOwnership; }
export interface AnyResourceEventMetadata { readonly event: HandlerEventType; readonly handlerIds: readonly import('./common.js').HandlerId[]; }
export interface ResourceInstanceInput<TSpec extends object> { readonly name: KubernetesName; readonly namespace?: NamespaceName; readonly spec: TSpec; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
export interface ResourceVersionDefinition<TSpec extends object, TStatus extends object> { readonly name: string; readonly served: boolean; readonly storage: boolean; readonly spec: RuntimeSchema<TSpec>; readonly status?: RuntimeSchema<TStatus>; readonly compatibility: VersionCompatibility; }
export interface VersionCompatibility { readonly conversionStrategy: import('./common.js').ConversionStrategy; readonly conversionWebhook?: WebhookReference; readonly deprecated?: boolean; readonly deprecationWarning?: string; }
export interface WebhookReference { readonly serviceName: KubernetesName; readonly serviceNamespace: NamespaceName; readonly path: string; readonly caBundleSecretRef?: SecretRef; }
export interface PrinterColumn { readonly name: string; readonly type: 'string' | 'integer' | 'number' | 'boolean' | 'date'; readonly jsonPath: string; readonly description?: string; readonly priority?: number; }
export interface PermissionRule { readonly apiGroups: readonly string[]; readonly resources: readonly string[]; readonly verbs: readonly string[]; readonly resourceNames?: readonly string[]; readonly scope?: ResourceScope; /** Connection-scoped permission envelope only; local RBAC ignores this field. */ readonly namespaces?: readonly NamespaceName[] | 'all'; }
export interface ResourcePermissionFactory { watch(): PermissionRule; read(): PermissionRule; apply(): PermissionRule; patch(): PermissionRule; patchStatus(): PermissionRule; delete(): PermissionRule; finalize(): PermissionRule; manage(): readonly PermissionRule[]; }
export interface LabelSelector { readonly matchLabels?: Readonly<Record<string, string>>; readonly matchExpressions?: readonly LabelSelectorRequirement[]; }
export interface LabelSelectorRequirement { readonly key: string; readonly operator: 'In' | 'NotIn' | 'Exists' | 'DoesNotExist'; readonly values?: readonly string[]; }
export interface ResourceClient<TSpec extends object, TStatus extends object> { create(object: KubernetesObject<TSpec, TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; read(ref: ObjectRef): Promise<Result<KubernetesObject<TSpec, TStatus>>>; list(query?: ListQuery): Promise<Result<readonly KubernetesObject<TSpec, TStatus>[]>>; update(object: KubernetesObject<TSpec, TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; patch(ref: ObjectRef, patch: JsonPatch): Promise<Result<KubernetesObject<TSpec, TStatus>>>; patchStatus(ref: ObjectRef, status: PartialStatus<TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; delete(ref: ObjectRef, options?: DeleteOptions): Promise<Result<DeleteResult>>; watch(query?: ListQuery): AsyncIterable<Result<WatchEvent<TSpec, TStatus>>>; }
export interface ListQuery { readonly namespace?: NamespaceName; readonly labelSelector?: LabelSelector; readonly fieldSelector?: string; readonly limit?: number; readonly continueToken?: string; }
export interface ResourceReadQuery { readonly namespace?: NamespaceName; readonly labels?: Readonly<Record<string, string>>; readonly labelSelector?: LabelSelector; readonly fieldSelector?: string; readonly limit?: number; readonly continueToken?: string; readonly orderBy?: 'metadata.name' | 'metadata.creationTimestamp'; }
export interface ResourceGetQuery { readonly name: KubernetesName; readonly namespace?: NamespaceName; }
export interface ResourceReadList<TSpec extends object, TStatus extends object> { readonly items: readonly ResourceObject<TSpec, TStatus>[]; readonly continueToken?: string; }
export interface ResourceReadClient<TSpec extends object, TStatus extends object> { get(query: ResourceGetQuery): Promise<ResourceObject<TSpec, TStatus> | undefined>; list(query?: ResourceReadQuery): Promise<ResourceReadList<TSpec, TStatus>>; }
export interface ResourceCounterIncrementInput<TSpec extends object> { readonly name: KubernetesName; readonly namespace?: NamespaceName; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; readonly spec?: Partial<TSpec>; readonly field?: string; readonly amount?: number; readonly flushMs?: number; }
export interface ResourceCounterIncrementResult { readonly buffered: true; readonly pending: number; }
export interface ResourceIndexOptions { readonly partitionBy?: unknown; readonly filter?: unknown; readonly orderBy?: unknown; }
export interface ResourceIndexQuery { readonly limit?: number; readonly cursor?: string; readonly namespace?: NamespaceName; }
export interface ResourceIndex<TSpec extends object, TStatus extends object> { readonly name: string; readonly resource: Pick<ResourceDefinition<TSpec, TStatus>, 'apiVersion' | 'kind' | 'plural' | 'scope'>; readonly options: ResourceIndexOptions; query(partition: string, query?: ResourceIndexQuery): Promise<ResourceReadList<TSpec, TStatus> & { readonly nextCursor?: string }>; }
export interface DeleteResult { readonly ref: ObjectRef; readonly deleted: boolean; }
export interface WatchEvent<TSpec extends object, TStatus extends object> { readonly type: WatchEventType; readonly object?: KubernetesObject<TSpec, TStatus>; }
