import type { ApiVersion, HandlerEventType, Kind, KubernetesName, NamespaceName, ObjectMeta, ObjectRef, PluralName, ResourceScope, Result, WatchEventType } from './common.js';
import type { SecretRef } from './capability.js';
import type { AnyRuntimeSchema, RuntimeSchema } from './schema.js';
import type { CapabilityClientSet } from './capability.js';
import type { DeleteOptions, JsonPatch, PartialStatus } from './operation-plan.js';
import type { ResourceEventSources } from './handler.js';

export interface KubernetesObject<TSpec extends object = import('./common.js').JsonObject, TStatus extends object = import('./common.js').JsonObject> { readonly apiVersion: ApiVersion; readonly kind: Kind; readonly metadata: ObjectMeta; readonly spec?: TSpec; readonly status?: TStatus; readonly [key: string]: unknown; }
export type AnyKubernetesObject = KubernetesObject<object, object>;
export type ResourceObject<TSpec extends object, TStatus extends object> = KubernetesObject<TSpec, TStatus> & { readonly spec: TSpec; };
export interface ResourceDefinition<TSpec extends object, TStatus extends object, TCapabilities extends CapabilityClientSet = CapabilityClientSet> { (input: ResourceInstanceInput<TSpec>): ResourceObject<TSpec, TStatus>; readonly apiVersion: ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly spec: RuntimeSchema<TSpec>; readonly status?: RuntimeSchema<TStatus>; readonly statusConvention?: import('./common.js').StatusConvention; readonly statusSubresource: boolean; readonly additionalPrinterColumns?: readonly PrinterColumn[]; readonly versions: readonly ResourceVersionDefinition<TSpec, TStatus>[]; readonly permissions: ResourcePermissionFactory; readonly on: ResourceEventSources<TSpec, TStatus, TCapabilities>; }
export interface AnyResourceVersionDefinition { readonly name: string; readonly served: boolean; readonly storage: boolean; readonly spec: AnyRuntimeSchema; readonly status?: AnyRuntimeSchema; readonly compatibility: VersionCompatibility; }
export interface AnyResourceDefinition<TCapabilities extends CapabilityClientSet = CapabilityClientSet> { readonly apiVersion: ApiVersion; readonly kind: Kind; readonly plural: PluralName; readonly scope: ResourceScope; readonly spec: AnyRuntimeSchema; readonly status?: AnyRuntimeSchema; readonly statusConvention?: import('./common.js').StatusConvention; readonly statusSubresource: boolean; readonly additionalPrinterColumns?: readonly PrinterColumn[]; readonly versions: readonly AnyResourceVersionDefinition[]; readonly permissions: ResourcePermissionFactory; readonly capabilityNames?: readonly (keyof TCapabilities & string)[]; readonly eventMetadata?: readonly AnyResourceEventMetadata[]; }
export interface AnyResourceEventMetadata { readonly event: HandlerEventType; readonly handlerIds: readonly import('./common.js').HandlerId[]; }
export interface ResourceInstanceInput<TSpec extends object> { readonly name: KubernetesName; readonly namespace?: NamespaceName; readonly spec: TSpec; readonly labels?: Readonly<Record<string, string>>; readonly annotations?: Readonly<Record<string, string>>; }
export interface ResourceVersionDefinition<TSpec extends object, TStatus extends object> { readonly name: string; readonly served: boolean; readonly storage: boolean; readonly spec: RuntimeSchema<TSpec>; readonly status?: RuntimeSchema<TStatus>; readonly compatibility: VersionCompatibility; }
export interface VersionCompatibility { readonly conversionStrategy: import('./common.js').ConversionStrategy; readonly conversionWebhook?: WebhookReference; readonly deprecated?: boolean; readonly deprecationWarning?: string; }
export interface WebhookReference { readonly serviceName: KubernetesName; readonly serviceNamespace: NamespaceName; readonly path: string; readonly caBundleSecretRef?: SecretRef; }
export interface PrinterColumn { readonly name: string; readonly type: 'string' | 'integer' | 'number' | 'boolean' | 'date'; readonly jsonPath: string; readonly description?: string; readonly priority?: number; }
export interface PermissionRule { readonly apiGroups: readonly string[]; readonly resources: readonly string[]; readonly verbs: readonly string[]; readonly resourceNames?: readonly string[]; }
export interface ResourcePermissionFactory { watch(): Result<PermissionRule>; read(): Result<PermissionRule>; apply(): Result<PermissionRule>; patch(): Result<PermissionRule>; patchStatus(): Result<PermissionRule>; delete(): Result<PermissionRule>; }
export interface LabelSelector { readonly matchLabels?: Readonly<Record<string, string>>; readonly matchExpressions?: readonly LabelSelectorRequirement[]; }
export interface LabelSelectorRequirement { readonly key: string; readonly operator: 'In' | 'NotIn' | 'Exists' | 'DoesNotExist'; readonly values?: readonly string[]; }
export interface ResourceClient<TSpec extends object, TStatus extends object> { create(object: KubernetesObject<TSpec, TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; read(ref: ObjectRef): Promise<Result<KubernetesObject<TSpec, TStatus>>>; list(query?: ListQuery): Promise<Result<readonly KubernetesObject<TSpec, TStatus>[]>>; update(object: KubernetesObject<TSpec, TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; patch(ref: ObjectRef, patch: JsonPatch): Promise<Result<KubernetesObject<TSpec, TStatus>>>; patchStatus(ref: ObjectRef, status: PartialStatus<TStatus>): Promise<Result<KubernetesObject<TSpec, TStatus>>>; delete(ref: ObjectRef, options?: DeleteOptions): Promise<Result<DeleteResult>>; watch(query?: ListQuery): AsyncIterable<Result<WatchEvent<TSpec, TStatus>>>; }
export interface ListQuery { readonly namespace?: NamespaceName; readonly labelSelector?: LabelSelector; readonly fieldSelector?: string; readonly limit?: number; readonly continueToken?: string; }
export interface DeleteResult { readonly ref: ObjectRef; readonly deleted: boolean; }
export interface WatchEvent<TSpec extends object, TStatus extends object> { readonly type: WatchEventType; readonly object?: KubernetesObject<TSpec, TStatus>; }
