import type { Diagnostic, GeneratedSchemaKind, JsonObject, JsonValue, PayloadSchemaKind, Result, SchemaSourceKind, Sha256Digest } from './common.js';

export type SchemaSource<T extends object> = ArkTypeSchemaSource<T> | JsonSchemaSource<T> | CustomSchemaSource<T>;
export interface SchemaSourceRef { readonly kind: SchemaSourceKind; readonly moduleSpecifier?: string; readonly exportName?: string; readonly digest?: Sha256Digest; }
export interface ArkTypeSchemaSource<T extends object> { readonly kind: 'arktype'; readonly ref: SchemaSourceRef; readonly inferredType?: T; }
export interface JsonSchemaSource<T extends object> { readonly kind: 'jsonSchema'; readonly ref: SchemaSourceRef; readonly schema: JsonObject; readonly inferredType?: T; }
export interface CustomSchemaSource<T extends object> { readonly kind: 'custom'; readonly ref: SchemaSourceRef; readonly validatorName: string; readonly inferredType?: T; }
export interface RuntimeSchema<T extends object> { readonly source: SchemaSource<T>; readonly contract: SchemaContract<T>; readonly description?: string; validate(value: JsonValue): Result<T>; emitOpenApiSchema(): Result<GeneratedSchemaArtifact>; emitJsonSchema(): Result<GeneratedSchemaArtifact>; }
export interface SchemaContract<T extends object> { readonly source: SchemaSourceRef; readonly typeScript: TypeScriptSchemaContract<T>; readonly runtimeValidation: RuntimeValidationContract; readonly kubernetesOpenApi: GeneratedSchemaContract; readonly jsonSchema: GeneratedSchemaContract; readonly equivalence: SchemaEquivalenceReport; }
export interface TypeScriptSchemaContract<T extends object> { readonly representation: 'inferred' | 'declared' | 'erased'; readonly inferredType?: T; readonly description?: string; }
export interface RuntimeValidationContract { readonly mode: 'authoritative' | 'structuralSubset' | 'objectOnly' | 'externalCustom'; readonly validatesUnknownFields: boolean; readonly diagnostics: readonly Diagnostic[]; }
export interface GeneratedSchemaContract { readonly mode: 'authoritative' | 'structuralSubset' | 'broadObjectFallback' | 'externalCustom'; readonly structural: KubernetesStructuralSchemaStatus; readonly diagnostics: readonly Diagnostic[]; }
export interface KubernetesStructuralSchemaStatus { readonly checked: boolean; readonly valid: boolean; readonly diagnostics: readonly Diagnostic[]; }
export interface SchemaEquivalenceReport { readonly typeScriptRuntimeAligned: boolean; readonly runtimeOpenApiAligned: boolean; readonly openApiJsonSchemaAligned: boolean; readonly discrepancies: readonly SchemaContractDiscrepancy[]; }
export interface SchemaContractDiscrepancy { readonly layer: 'typeScript' | 'runtimeValidation' | 'kubernetesOpenApi' | 'jsonSchema'; readonly severity: Diagnostic['severity']; readonly code: Diagnostic['code']; readonly message: string; }
export interface GeneratedSchemaArtifact { readonly kind: GeneratedSchemaKind; readonly source: SchemaSourceRef; readonly schema: JsonObject; readonly diagnostics: readonly Diagnostic[]; }
export interface PayloadSchemaArtifact { readonly kind: PayloadSchemaKind; readonly jsonSchema: GeneratedSchemaArtifact; readonly sourceType: string; readonly digest: Sha256Digest; }
export interface RuntimePayloadSchemas { readonly handlerInput: PayloadSchemaArtifact; readonly normalizedOperationPlan: PayloadSchemaArtifact; readonly operatorManifest: PayloadSchemaArtifact; readonly handlerError: PayloadSchemaArtifact; readonly capabilityRequest: PayloadSchemaArtifact; readonly capabilityResponse: PayloadSchemaArtifact; }
export interface RuntimePayloadSchemaDigests { readonly handlerInput: Sha256Digest; readonly normalizedOperationPlan: Sha256Digest; readonly operatorManifest: Sha256Digest; readonly handlerError: Sha256Digest; readonly capabilityRequest: Sha256Digest; readonly capabilityResponse: Sha256Digest; }
export interface OpenApiSchema { readonly type?: 'object' | 'array' | 'string' | 'number' | 'integer' | 'boolean'; readonly properties?: Readonly<Record<string, OpenApiSchema>>; readonly items?: OpenApiSchema; readonly required?: readonly string[]; readonly enum?: readonly JsonValue[]; readonly nullable?: boolean; readonly additionalProperties?: boolean | OpenApiSchema; readonly description?: string; readonly default?: JsonValue; readonly xKubernetesValidations?: readonly KubernetesCelValidation[]; readonly xKubernetesListType?: 'atomic' | 'set' | 'map'; readonly xKubernetesMapType?: 'atomic' | 'granular'; readonly xKubernetesPreserveUnknownFields?: boolean; }
export interface KubernetesCelValidation { readonly rule: string; readonly message?: string; readonly reason?: string; readonly fieldPath?: string; }
export interface AnyRuntimeSchema { readonly contract: SchemaContract<object>; readonly description?: string; validate(value: JsonValue): Result<object>; emitOpenApiSchema(): Result<GeneratedSchemaArtifact>; emitJsonSchema(): Result<GeneratedSchemaArtifact>; }
