// Generated by scripts/generate-v09-public-contract-inventory.ts.
// Do not edit by hand.
export interface PublicDiagnosticRecord {
  readonly code: string;
  readonly owner: string;
  readonly sources: readonly string[];
  readonly documentation: string;
}

export const publicDiagnosticRecords = Object.freeze([
  {
    "code": "ABI_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-abi-incompatible"
  },
  {
    "code": "ADMISSION_AUTHORITY_MISMATCH",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-authority-mismatch"
  },
  {
    "code": "ADMISSION_CONTEXT_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-context-invalid"
  },
  {
    "code": "ADMISSION_DEADLINE_EXPIRED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-deadline-expired"
  },
  {
    "code": "ADMISSION_IDENTITY_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-identity-invalid"
  },
  {
    "code": "ADMISSION_OPERATION_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-operation-invalid"
  },
  {
    "code": "ADMISSION_RECEIPT_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-receipt-invalid"
  },
  {
    "code": "ADMISSION_TRACE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-trace-invalid"
  },
  {
    "code": "ADMISSION_VERSION_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-admission-version-invalid"
  },
  {
    "code": "APPLIK8S_SAGA_DATABASE_URL",
    "owner": "package:@applik8s/compiler",
    "sources": [
      "packages/compiler/src/application-workflows/contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-applik8s-saga-database-url"
  },
  {
    "code": "AUTHORITY_BOUND_FIELD_OVERRIDE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/task-operation-runtime.ts",
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-bound-field-override"
  },
  {
    "code": "AUTHORITY_BREAK_GLASS_ACKNOWLEDGEMENT_REQUIRED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-break-glass-acknowledgement-required"
  },
  {
    "code": "AUTHORITY_CATALOG_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-catalog-incompatible"
  },
  {
    "code": "AUTHORITY_CATALOG_MIGRATION_INVALID",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-catalog-migration-invalid"
  },
  {
    "code": "AUTHORITY_DELEGATION_BROADENING",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/core/src/application-operation-authority.ts",
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-delegation-broadening"
  },
  {
    "code": "AUTHORITY_DELEGATION_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-delegation-unavailable"
  },
  {
    "code": "AUTHORITY_DUPLICATE_OPERATION",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-duplicate-operation"
  },
  {
    "code": "AUTHORITY_EXECUTION_BINDING_INVALID",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/task-operation-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-execution-binding-invalid"
  },
  {
    "code": "AUTHORITY_EXECUTION_BINDING_MISSING",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/task-operation-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-execution-binding-missing"
  },
  {
    "code": "AUTHORITY_GRANT_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-grant-conflict"
  },
  {
    "code": "AUTHORITY_GRANT_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-grant-unavailable"
  },
  {
    "code": "AUTHORITY_INVALID_OPERATION_ID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-invalid-operation-id"
  },
  {
    "code": "AUTHORITY_INVALID_RESERVATION_TRANSITION",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-invalid-reservation-transition"
  },
  {
    "code": "AUTHORITY_INVALID_SCOPE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/core/src/application-operation-authority.ts",
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-invalid-scope"
  },
  {
    "code": "AUTHORITY_MANIFEST_IDENTITY_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-manifest-identity-conflict"
  },
  {
    "code": "AUTHORITY_MANIFEST_REVISION_MISMATCH",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-manifest-revision-mismatch"
  },
  {
    "code": "AUTHORITY_ORIGIN_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-origin-conflict"
  },
  {
    "code": "AUTHORITY_OUTCOME_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-outcome-conflict"
  },
  {
    "code": "AUTHORITY_OUTCOME_SELF_VERIFICATION",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-outcome-self-verification"
  },
  {
    "code": "AUTHORITY_OUTCOME_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-outcome-unavailable"
  },
  {
    "code": "AUTHORITY_PERMISSION_NOT_GRANTABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-permission-not-grantable"
  },
  {
    "code": "AUTHORITY_PERMISSION_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-permission-unavailable"
  },
  {
    "code": "AUTHORITY_REQUEST_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-request-conflict"
  },
  {
    "code": "AUTHORITY_REQUEST_INVALID_STATE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-request-invalid-state"
  },
  {
    "code": "AUTHORITY_REQUEST_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-request-unavailable"
  },
  {
    "code": "AUTHORITY_RESERVATION_NOT_FOUND",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-reservation-not-found"
  },
  {
    "code": "AUTHORITY_RESERVATION_REQUIRED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-reservation-required"
  },
  {
    "code": "AUTHORITY_RETIRED_OPERATION",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-retired-operation"
  },
  {
    "code": "AUTHORITY_REVOCATION_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-revocation-conflict"
  },
  {
    "code": "AUTHORITY_REVOCATION_INVALID_STATE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-revocation-invalid-state"
  },
  {
    "code": "AUTHORITY_REVOCATION_PENDING",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/core/src/application-operation-authority.ts",
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-revocation-pending"
  },
  {
    "code": "AUTHORITY_REVOCATION_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-revocation-unavailable"
  },
  {
    "code": "AUTHORITY_SCOPE_CONFLICT",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-scope-conflict"
  },
  {
    "code": "AUTHORITY_SELF_APPROVAL",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-self-approval"
  },
  {
    "code": "AUTHORITY_SELF_GRANT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-self-grant"
  },
  {
    "code": "AUTHORITY_UNCLASSIFIED_OPERATION",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-operation-authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authority-unclassified-operation"
  },
  {
    "code": "AUTHORIZATION_AUDIENCE_DENIED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-audience-denied"
  },
  {
    "code": "AUTHORIZATION_CATALOG_INACTIVE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-catalog-inactive"
  },
  {
    "code": "AUTHORIZATION_CONTEXT_MISMATCH",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-context-mismatch"
  },
  {
    "code": "AUTHORIZATION_GRANT_EXHAUSTED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-grant-exhausted"
  },
  {
    "code": "AUTHORIZATION_GRANT_EXPIRED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-grant-expired"
  },
  {
    "code": "AUTHORIZATION_GRANT_REVOKED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-grant-revoked"
  },
  {
    "code": "AUTHORIZATION_NO_GRANT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-no-grant"
  },
  {
    "code": "AUTHORIZATION_OPERATION_MISMATCH",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts",
      "packages/operations/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-operation-mismatch"
  },
  {
    "code": "AUTHORIZATION_OPERATION_UNCLASSIFIED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-operation-unclassified"
  },
  {
    "code": "AUTHORIZATION_POLICY_DENIED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-policy-denied"
  },
  {
    "code": "AUTHORIZATION_SCOPE_EMPTY",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-scope-empty"
  },
  {
    "code": "AUTHORIZATION_TRANSPORT_DENIED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/authority.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-authorization-transport-denied"
  },
  {
    "code": "AWS_CONFIGURATION_UNRESOLVED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/aws-deployment-plan.ts",
      "packages/deployment-contract/src/aws-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-aws-configuration-unresolved"
  },
  {
    "code": "AWS_COST_BOUND_EXCEEDED",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/aws-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-aws-cost-bound-exceeded"
  },
  {
    "code": "AWS_PROVIDER_INCOMPATIBLE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/aws-deployment-plan.ts",
      "packages/deployment-contract/src/aws-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-aws-provider-incompatible"
  },
  {
    "code": "AWS_RUNTIME_ACCESS_UNRESOLVED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/aws-deployment-plan.ts",
      "packages/deployment-contract/src/aws-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-aws-runtime-access-unresolved"
  },
  {
    "code": "AWS_SENSITIVE_DATA",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/aws-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-aws-sensitive-data"
  },
  {
    "code": "BUNDLE_INVALID",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/compiler/src/bundling/index.ts",
      "packages/compiler/src/container-image/index.ts",
      "packages/compiler/src/kubernetes-yaml/index.ts",
      "packages/compiler/src/manifest/index.ts",
      "packages/compiler/src/pipeline/entrypoint-discovery.ts",
      "packages/compiler/src/pipeline/index.ts",
      "packages/compiler/src/pipeline/pipeline-selection.ts",
      "packages/compiler/src/pipeline/pipeline-shapes.ts",
      "packages/compiler/src/pipeline/static-dispatcher.ts",
      "packages/compiler/src/pipeline/static-serialization.ts",
      "packages/compiler/src/runtime-contract/index.ts",
      "packages/compiler/src/wasm-component/index.ts",
      "packages/core/src/common.ts",
      "packages/typekro-adapter/src/operation-targets.ts",
      "packages/typekro-adapter/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-bundle-invalid"
  },
  {
    "code": "CANCELLATION_PENDING",
    "owner": "package:@applik8s/runtime-aws",
    "sources": [
      "packages/runtime-aws/src/lakehouse.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-cancellation-pending"
  },
  {
    "code": "CANONICAL_JSON_CYCLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/canonical-json.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-canonical-json-cycle"
  },
  {
    "code": "CANONICAL_JSON_NON_FINITE_NUMBER",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/canonical-json.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-canonical-json-non-finite-number"
  },
  {
    "code": "CANONICAL_JSON_UNDEFINED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/canonical-json.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-canonical-json-undefined"
  },
  {
    "code": "CANONICAL_JSON_UNSUPPORTED_VALUE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/canonical-json.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-canonical-json-unsupported-value"
  },
  {
    "code": "CAPABILITY_DENIED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/core/src/common.ts",
      "packages/sdk/src/handler-dispatch.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-capability-denied"
  },
  {
    "code": "CAPABILITY_MISSING",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/dns.ts",
      "packages/core/src/common.ts",
      "packages/testing/src/harness.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-capability-missing"
  },
  {
    "code": "CATALOG_INCOMPATIBLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-incompatible"
  },
  {
    "code": "CATALOG_INVALID",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-invalid"
  },
  {
    "code": "CATALOG_INVALID_STATE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-invalid-state"
  },
  {
    "code": "CATALOG_NOT_FOUND",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-not-found"
  },
  {
    "code": "CATALOG_OPERATION_UNAVAILABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-operation-unavailable"
  },
  {
    "code": "CATALOG_PREDECESSOR_MISMATCH",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-predecessor-mismatch"
  },
  {
    "code": "CATALOG_REFERENCED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-referenced"
  },
  {
    "code": "CATALOG_REVISION_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/catalog.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-catalog-revision-conflict"
  },
  {
    "code": "COMPATIBILITY_FAILED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/compiler/src/pipeline/index.ts",
      "packages/core/src/application-graph-compatibility.ts",
      "packages/core/src/application-graph-contract.ts",
      "packages/core/src/application-graph-node-validation.ts",
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-compatibility-failed"
  },
  {
    "code": "DEPLOYMENT_CONNECTION_UNSAFE",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-connection-unsafe"
  },
  {
    "code": "DEPLOYMENT_EDGE_CYCLE",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-edge-cycle"
  },
  {
    "code": "DEPLOYMENT_EDGE_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-edge-invalid"
  },
  {
    "code": "DEPLOYMENT_GRAPH_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-graph-invalid"
  },
  {
    "code": "DEPLOYMENT_IDENTITY_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-identity-invalid"
  },
  {
    "code": "DEPLOYMENT_LIFECYCLE_UNSAFE",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-lifecycle-unsafe"
  },
  {
    "code": "DEPLOYMENT_NODE_DUPLICATE",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-node-duplicate"
  },
  {
    "code": "DEPLOYMENT_NODE_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-node-invalid"
  },
  {
    "code": "DEPLOYMENT_OUTPUT_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-output-invalid"
  },
  {
    "code": "DEPLOYMENT_SECRET_UNSAFE",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-secret-unsafe"
  },
  {
    "code": "DEPLOYMENT_SINGLETON_DRIFT",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-singleton-drift"
  },
  {
    "code": "DEPLOYMENT_STATUS_INVALID",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-status-invalid"
  },
  {
    "code": "DEPLOYMENT_STRATEGY_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-contract",
    "sources": [
      "packages/deployment-contract/src/types.ts",
      "packages/deployment-contract/src/validation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-deployment-strategy-unsupported"
  },
  {
    "code": "DEVELOPMENT_AGENT_TURN_FAILED",
    "owner": "package:@applik8s/dev",
    "sources": [
      "packages/dev/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-development-agent-turn-failed"
  },
  {
    "code": "EFFECT_FENCE_UNSUPPORTED",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/effect-contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-effect-fence-unsupported"
  },
  {
    "code": "EFFECT_IDENTITY_UNSTABLE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/effect-contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-effect-identity-unstable"
  },
  {
    "code": "EFFECT_RECEIPT_CONFLICT",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/effect-contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-effect-receipt-conflict"
  },
  {
    "code": "EFFECT_RETRY_UNSAFE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/effect-contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-effect-retry-unsafe"
  },
  {
    "code": "EXECUTION_ADMISSION_INVALID",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/execution-admission-transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-execution-admission-invalid"
  },
  {
    "code": "EXECUTION_ADMISSION_TOO_LARGE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/execution-admission-transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-execution-admission-too-large"
  },
  {
    "code": "FINALIZER_FAILED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-finalizer-failed"
  },
  {
    "code": "FLOW_BINDING_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-flow-binding-invalid"
  },
  {
    "code": "FLOW_RATE_LIMITED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-flow-rate-limited"
  },
  {
    "code": "FLOW_TRANSITION_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-flow-transition-invalid"
  },
  {
    "code": "FLOW_UNAVAILABLE",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-flow-unavailable"
  },
  {
    "code": "FOUNDATION_GUEST_HOST_ENVELOPE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-guest-host-envelope-invalid"
  },
  {
    "code": "FOUNDATION_IDENTITY_DUPLICATE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-identity-duplicate"
  },
  {
    "code": "FOUNDATION_IDENTITY_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-identity-invalid"
  },
  {
    "code": "FOUNDATION_NATIVE_PLAN_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-native-plan-invalid"
  },
  {
    "code": "FOUNDATION_PROVENANCE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-provenance-invalid"
  },
  {
    "code": "FOUNDATION_PROVIDER_GUARANTEE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-provider-guarantee-invalid"
  },
  {
    "code": "FOUNDATION_RUNTIME_ACCESS_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-runtime-access-invalid"
  },
  {
    "code": "FOUNDATION_TARGET_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-foundation.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-foundation-target-invalid"
  },
  {
    "code": "HANDLER_NOT_FOUND",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-handler-not-found"
  },
  {
    "code": "HANDLER_OUTPUT_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-handler-output-invalid"
  },
  {
    "code": "HANDLER_TIMEOUT",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-handler-timeout"
  },
  {
    "code": "HANDLER_TRAP",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-handler-trap"
  },
  {
    "code": "INTERNAL_INVOCATION_INVALID",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/internal-transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-internal-invocation-invalid"
  },
  {
    "code": "INTERNAL_INVOCATION_TOO_LARGE",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/internal-transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-internal-invocation-too-large"
  },
  {
    "code": "INTERNAL_TOKEN_PASSTHROUGH_FORBIDDEN",
    "owner": "package:@applik8s/operations",
    "sources": [
      "packages/operations/src/internal-transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-internal-token-passthrough-forbidden"
  },
  {
    "code": "JOB_EXECUTION_DEADLINE_EXCEEDED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-finite-jobs.ts",
      "packages/applik8s/src/application-job-durable-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-job-execution-deadline-exceeded"
  },
  {
    "code": "JOB_EXECUTION_FAILED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-finite-jobs.ts",
      "packages/applik8s/src/application-job-durable-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-job-execution-failed"
  },
  {
    "code": "JOB_LEASE_LOST",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-job-store.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-job-lease-lost"
  },
  {
    "code": "JOB_STORE_INVARIANT",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-job-store.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-job-store-invariant"
  },
  {
    "code": "JOB_WORKER_STOPPED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-job-durable-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-job-worker-stopped"
  },
  {
    "code": "JOURNEY_ASSERTION_TIMEOUT",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-assertion-timeout"
  },
  {
    "code": "JOURNEY_AUTHORITY_SETUP_FAILED",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-authority-setup-failed"
  },
  {
    "code": "JOURNEY_CLEANUP_INCOMPLETE",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-cleanup-incomplete"
  },
  {
    "code": "JOURNEY_DEPENDENCY_UNRESOLVED",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-dependency-unresolved"
  },
  {
    "code": "JOURNEY_EVIDENCE_REDACTION_FAILED",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-evidence-redaction-failed"
  },
  {
    "code": "JOURNEY_FIXTURE_UNAVAILABLE",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-fixture-unavailable"
  },
  {
    "code": "JOURNEY_PROVIDER_INCOMPATIBLE",
    "owner": "package:@applik8s/testing",
    "sources": [
      "packages/testing/src/journey.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-journey-provider-incompatible"
  },
  {
    "code": "KUBERNETES_API_ERROR",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-api-error"
  },
  {
    "code": "KUBERNETES_CLUSTER_AUTHORITY_UNDECLARED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-authority-undeclared"
  },
  {
    "code": "KUBERNETES_CLUSTER_BINDING_MISSING",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-binding-missing"
  },
  {
    "code": "KUBERNETES_CLUSTER_CANCELLED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-cancelled"
  },
  {
    "code": "KUBERNETES_CLUSTER_CONFLICT",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/runtime-kubernetes/src/cluster-capability.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-conflict"
  },
  {
    "code": "KUBERNETES_CLUSTER_CONTINUATION_INVALID",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-continuation-invalid"
  },
  {
    "code": "KUBERNETES_CLUSTER_DEADLINE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/runtime-kubernetes/src/cluster-capability.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-deadline"
  },
  {
    "code": "KUBERNETES_CLUSTER_ENDPOINT_FORBIDDEN",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-endpoint-forbidden"
  },
  {
    "code": "KUBERNETES_CLUSTER_FORBIDDEN",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/runtime-kubernetes/src/cluster-capability.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-forbidden"
  },
  {
    "code": "KUBERNETES_CLUSTER_LIST_UNBOUNDED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-list-unbounded"
  },
  {
    "code": "KUBERNETES_CLUSTER_MUTATION_OWNERSHIP_REQUIRED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-mutation-ownership-required"
  },
  {
    "code": "KUBERNETES_CLUSTER_NOT_FOUND",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/runtime-kubernetes/src/cluster-capability.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-not-found"
  },
  {
    "code": "KUBERNETES_CLUSTER_PROTOCOL_INCOMPATIBLE",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/applik8s/src/kubernetes-cluster-wit-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-protocol-incompatible"
  },
  {
    "code": "KUBERNETES_CLUSTER_RESPONSE_LIMIT",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-response-limit"
  },
  {
    "code": "KUBERNETES_CLUSTER_SCHEMA_MISMATCH",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-schema-mismatch"
  },
  {
    "code": "KUBERNETES_CLUSTER_SCOPE_UNBOUNDED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-scope-unbounded"
  },
  {
    "code": "KUBERNETES_CLUSTER_UNAVAILABLE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/kubernetes-cluster-runtime.ts",
      "packages/applik8s/src/kubernetes-cluster-wit-runtime.ts",
      "packages/runtime-kubernetes/src/cluster-capability.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-kubernetes-cluster-unavailable"
  },
  {
    "code": "LIFECYCLE_UNSAFE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/application-builder.ts",
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-lifecycle-unsafe"
  },
  {
    "code": "LOCAL_CAPABILITY_UNBOUND",
    "owner": "package:@applik8s/server",
    "sources": [
      "packages/server/src/local-operator-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-local-capability-unbound"
  },
  {
    "code": "LOCAL_KUBERNETES_READ_FAILED",
    "owner": "package:@applik8s/server",
    "sources": [
      "packages/server/src/local-operator-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-local-kubernetes-read-failed"
  },
  {
    "code": "LOCAL_LIFECYCLE_COLLISION",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/local-supervisor-plan.ts",
      "packages/deployment-contract/src/local-supervisor.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-local-lifecycle-collision"
  },
  {
    "code": "LOCAL_PROVIDER_UNRESOLVED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/local-supervisor-plan.ts",
      "packages/deployment-contract/src/local-supervisor.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-local-provider-unresolved"
  },
  {
    "code": "LOCAL_TARGET_INCOMPATIBLE",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/local-supervisor-plan.ts",
      "packages/deployment-contract/src/local-supervisor.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-local-target-incompatible"
  },
  {
    "code": "MANIFEST_INVALID",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/compiler/src/kubernetes-schema/index.ts",
      "packages/compiler/src/kubernetes-yaml/index.ts",
      "packages/compiler/src/manifest/validation.ts",
      "packages/core/src/application-graph-contract.ts",
      "packages/core/src/common.ts",
      "packages/testing/src/proxy.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-manifest-invalid"
  },
  {
    "code": "MCP_AUTHENTICATION_REQUIRED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-authentication-required"
  },
  {
    "code": "MCP_AUTHORIZATION_DENIED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/placement.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-authorization-denied"
  },
  {
    "code": "MCP_CATALOG_REINITIALIZE_REQUIRED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-catalog-reinitialize-required"
  },
  {
    "code": "MCP_DEADLINE_EXCEEDED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-deadline-exceeded"
  },
  {
    "code": "MCP_EXTERNAL_CREDENTIAL_INVALID",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-external-credential-invalid"
  },
  {
    "code": "MCP_EXTERNAL_SCHEMA_CHANGED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-external-schema-changed"
  },
  {
    "code": "MCP_EXTERNAL_UNAVAILABLE",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-external-unavailable"
  },
  {
    "code": "MCP_INPUT_INVALID",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/placement.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-input-invalid"
  },
  {
    "code": "MCP_PROTOCOL_UNSUPPORTED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-protocol-unsupported"
  },
  {
    "code": "MCP_REQUEST_TOO_LARGE",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-request-too-large"
  },
  {
    "code": "MCP_RESPONSE_TOO_LARGE",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-response-too-large"
  },
  {
    "code": "MCP_SESSION_IDENTITY_MISMATCH",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-session-identity-mismatch"
  },
  {
    "code": "MCP_SESSION_REQUIRED",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-session-required"
  },
  {
    "code": "MCP_SESSION_UNAVAILABLE",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-session-unavailable"
  },
  {
    "code": "MCP_TOOL_AMBIGUOUS",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-tool-ambiguous"
  },
  {
    "code": "MCP_TOOL_UNAVAILABLE",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-tool-unavailable"
  },
  {
    "code": "MCP_TOOL_UNKNOWN",
    "owner": "package:@applik8s/mcp",
    "sources": [
      "packages/mcp/src/client.ts",
      "packages/mcp/src/contracts.ts",
      "packages/mcp/src/server.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-mcp-tool-unknown"
  },
  {
    "code": "MIGRATION_CONCURRENT_OPERATION",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-concurrent-operation"
  },
  {
    "code": "MIGRATION_FORWARD_RECOVERY_REQUIRED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-forward-recovery-required"
  },
  {
    "code": "MIGRATION_LIFECYCLE_TRANSFER_UNSAFE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts",
      "packages/core/src/application-deployment-migration.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-lifecycle-transfer-unsafe"
  },
  {
    "code": "MIGRATION_MAPPING_AMBIGUOUS",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-mapping-ambiguous"
  },
  {
    "code": "MIGRATION_PHYSICAL_IDENTITY_CONFLICT",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-physical-identity-conflict"
  },
  {
    "code": "MIGRATION_PROVIDER_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts",
      "packages/core/src/application-deployment-migration.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-provider-incompatible"
  },
  {
    "code": "MIGRATION_RETAINED_DATA_UNSAFE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-retained-data-unsafe"
  },
  {
    "code": "MIGRATION_ROLLBACK_UNAVAILABLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-rollback-unavailable"
  },
  {
    "code": "MIGRATION_SHARED_OWNER_BLOCKED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-shared-owner-blocked"
  },
  {
    "code": "MIGRATION_SOURCE_RELEASE_UNQUALIFIED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-source-release-unqualified"
  },
  {
    "code": "MIGRATION_SOURCE_SCHEMA_UNSUPPORTED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-source-schema-unsupported"
  },
  {
    "code": "MIGRATION_SOURCE_STATE_MISSING",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-deployment-migration-proposal.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-migration-source-state-missing"
  },
  {
    "code": "ML_ARTIFACT_INTEGRITY_FAILED",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-artifact-integrity-failed"
  },
  {
    "code": "ML_DATA_RESIDENCY_UNSATISFIED",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-data-residency-unsatisfied"
  },
  {
    "code": "ML_INPUT_INVALID",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-input-invalid"
  },
  {
    "code": "ML_MODEL_VERSION_UNAVAILABLE",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-model-version-unavailable"
  },
  {
    "code": "ML_OUTPUT_INVALID",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-output-invalid"
  },
  {
    "code": "ML_PROVIDER_FAILED",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-provider-failed"
  },
  {
    "code": "ML_TIMEOUT",
    "owner": "package:@applik8s/ml",
    "sources": [
      "packages/ml/src/index.ts",
      "packages/ml/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ml-timeout"
  },
  {
    "code": "OAUTH_AUDIENCE_DENIED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-audience-denied"
  },
  {
    "code": "OAUTH_AUTHENTICATION_REQUIRED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-authentication-required"
  },
  {
    "code": "OAUTH_CLIENT_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-client-invalid"
  },
  {
    "code": "OAUTH_FLOW_BINDING_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-flow-binding-invalid"
  },
  {
    "code": "OAUTH_FLOW_UNAVAILABLE",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-flow-unavailable"
  },
  {
    "code": "OAUTH_PRINCIPAL_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-principal-invalid"
  },
  {
    "code": "OAUTH_PROVIDER_DECISION_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-provider-decision-invalid"
  },
  {
    "code": "OAUTH_REQUEST_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-request-invalid"
  },
  {
    "code": "OAUTH_RESOURCE_OWNER_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/oauth-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-resource-owner-invalid"
  },
  {
    "code": "OAUTH_SCOPE_DENIED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-scope-denied"
  },
  {
    "code": "OAUTH_TOKEN_EXPIRED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-token-expired"
  },
  {
    "code": "OAUTH_TOKEN_IDENTITY_MISSING",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-token-identity-missing"
  },
  {
    "code": "OAUTH_TOKEN_INACTIVE",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-token-inactive"
  },
  {
    "code": "OAUTH_TOKEN_LOCATION_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-token-location-invalid"
  },
  {
    "code": "OAUTH_TOKEN_TOO_LARGE",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/resource-admission.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-oauth-token-too-large"
  },
  {
    "code": "ORY_CANCELLED",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-cancelled"
  },
  {
    "code": "ORY_REQUEST_REJECTED",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/hydra.ts",
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-request-rejected"
  },
  {
    "code": "ORY_RESPONSE_INVALID",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/hydra.ts",
      "packages/identity-ory/src/keto.ts",
      "packages/identity-ory/src/kratos.ts",
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-response-invalid"
  },
  {
    "code": "ORY_TIMEOUT",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-timeout"
  },
  {
    "code": "ORY_UNAUTHORIZED",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/kratos.ts",
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-unauthorized"
  },
  {
    "code": "ORY_UNAVAILABLE",
    "owner": "package:@applik8s/identity-ory",
    "sources": [
      "packages/identity-ory/src/transport.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-ory-unavailable"
  },
  {
    "code": "OUTCOME_UNKNOWN",
    "owner": "package:@applik8s/runtime-aws",
    "sources": [
      "packages/runtime-aws/src/lakehouse.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-outcome-unknown"
  },
  {
    "code": "PARTIAL_APPLY_FAILED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-partial-apply-failed"
  },
  {
    "code": "PLAN_ACTOR_CAPABILITY_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-actor-capability-unsupported"
  },
  {
    "code": "PLAN_COMPARISON_APPLICATION_MISMATCH",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-comparison-application-mismatch"
  },
  {
    "code": "PLAN_COMPARISON_GRAPH_VERSION_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-comparison-graph-version-incompatible"
  },
  {
    "code": "PLAN_COMPARISON_SCHEMA_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-comparison-schema-incompatible"
  },
  {
    "code": "PLAN_IMPLEMENTATION_GRAPH_MISMATCH",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-implementation-graph-mismatch"
  },
  {
    "code": "PLAN_IMPLEMENTATION_PROFILE_MISMATCH",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-implementation-profile-mismatch"
  },
  {
    "code": "PLAN_PHYSICAL_CONTRIBUTOR_UNDECLARED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-physical-contributor-undeclared"
  },
  {
    "code": "PLAN_PHYSICAL_IMPLEMENTATION_AMBIGUOUS",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-physical-implementation-ambiguous"
  },
  {
    "code": "PLAN_PHYSICAL_IMPLEMENTATION_UNKNOWN",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/application-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-plan-physical-implementation-unknown"
  },
  {
    "code": "PROFILE_BINDING_CONFLICT",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-profile-binding-conflict"
  },
  {
    "code": "PROVIDER_COMPLETION_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-completion-invalid"
  },
  {
    "code": "PROVIDER_CONFIGURATION_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-configuration-invalid"
  },
  {
    "code": "PROVIDER_CONTINUITY_INVALID",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-continuity-invalid"
  },
  {
    "code": "PROVIDER_DEPENDENCY_CYCLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-dependency-cycle"
  },
  {
    "code": "PROVIDER_DEPENDENCY_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-dependency-incompatible"
  },
  {
    "code": "PROVIDER_DEPENDENCY_MISSING",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-dependency-missing"
  },
  {
    "code": "PROVIDER_IMPLEMENTATION_IDENTITY_COLLISION",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-implementation-identity-collision"
  },
  {
    "code": "PROVIDER_IMPLEMENTATION_IDENTITY_UNSTABLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-implementation-plan.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-implementation-identity-unstable"
  },
  {
    "code": "PROVIDER_SESSION_ORPHANED",
    "owner": "package:@applik8s/identity",
    "sources": [
      "packages/identity/src/runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-provider-session-orphaned"
  },
  {
    "code": "QUERY_BATCH_CANCELLED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/application-query-batching.ts",
      "packages/runtime-postgres/src/query-batch.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-query-batch-cancelled"
  },
  {
    "code": "RBAC_DENIED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-rbac-denied"
  },
  {
    "code": "RESEARCH_EVIDENCE_INCOMPLETE",
    "owner": "package:@applik8s/research",
    "sources": [
      "packages/research/src/agent-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-research-evidence-incomplete"
  },
  {
    "code": "RESEARCH_QUERY_INVALID",
    "owner": "package:@applik8s/research",
    "sources": [
      "packages/research/src/agent-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-research-query-invalid"
  },
  {
    "code": "RESOURCE_CONFLICT",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/dns.ts",
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-resource-conflict"
  },
  {
    "code": "RESOURCE_NOT_FOUND",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-resource-not-found"
  },
  {
    "code": "RUNTIME_ACCESS_BOOTSTRAP_IAM_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-bootstrap-iam-missing"
  },
  {
    "code": "RUNTIME_ACCESS_BOOTSTRAP_IAM_WIDENED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-bootstrap-iam-widened"
  },
  {
    "code": "RUNTIME_ACCESS_CREDENTIAL_CROSS_NAMESPACE",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-credential-cross-namespace"
  },
  {
    "code": "RUNTIME_ACCESS_CREDENTIAL_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-credential-missing"
  },
  {
    "code": "RUNTIME_ACCESS_CREDENTIAL_WIDENED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-credential-widened"
  },
  {
    "code": "RUNTIME_ACCESS_EXECUTION_ROLE_MISBOUND",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-execution-role-misbound"
  },
  {
    "code": "RUNTIME_ACCESS_EXECUTION_ROLE_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-execution-role-missing"
  },
  {
    "code": "RUNTIME_ACCESS_EXPLICIT_REDUNDANT",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-explicit-redundant"
  },
  {
    "code": "RUNTIME_ACCESS_EXPLICIT_UNUSED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-explicit-unused"
  },
  {
    "code": "RUNTIME_ACCESS_EXPLICIT_WIDENING",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-explicit-widening"
  },
  {
    "code": "RUNTIME_ACCESS_IAM_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-iam-missing"
  },
  {
    "code": "RUNTIME_ACCESS_IAM_WIDENED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-iam-widened"
  },
  {
    "code": "RUNTIME_ACCESS_NETWORK_MISBOUND",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-network-misbound"
  },
  {
    "code": "RUNTIME_ACCESS_NETWORK_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-network-missing"
  },
  {
    "code": "RUNTIME_ACCESS_NETWORK_WIDENED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-network-widened"
  },
  {
    "code": "RUNTIME_ACCESS_NETWORK_WRONG_PORT",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-network-wrong-port"
  },
  {
    "code": "RUNTIME_ACCESS_NETWORK_WRONG_PROTOCOL",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-network-wrong-protocol"
  },
  {
    "code": "RUNTIME_ACCESS_PROVIDER_GUARANTEE_UNSUPPORTED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-provider-guarantee-unsupported"
  },
  {
    "code": "RUNTIME_ACCESS_RBAC_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-rbac-missing"
  },
  {
    "code": "RUNTIME_ACCESS_RBAC_WIDENED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-rbac-widened"
  },
  {
    "code": "RUNTIME_ACCESS_ROLE_MISBOUND",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-role-misbound"
  },
  {
    "code": "RUNTIME_ACCESS_ROLE_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-role-missing"
  },
  {
    "code": "RUNTIME_ACCESS_SERVICE_ACCOUNT_MISMATCH",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-service-account-mismatch"
  },
  {
    "code": "RUNTIME_ACCESS_TARGET_UNRESOLVED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-target-unresolved"
  },
  {
    "code": "RUNTIME_ACCESS_WILDCARD_FORBIDDEN",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/deployment-compiler/src/runtime-access-plan.ts",
      "packages/deployment-contract/src/runtime-access.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-wildcard-forbidden"
  },
  {
    "code": "RUNTIME_ACCESS_WORKLOAD_MISSING",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/aws-runtime-access-parity.ts",
      "packages/deployment-compiler/src/kubernetes-runtime-access-parity.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-access-workload-missing"
  },
  {
    "code": "RUNTIME_INCOMPATIBLE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-runtime-incompatible"
  },
  {
    "code": "SAGA_COMPENSATED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-sagas.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-saga-compensated"
  },
  {
    "code": "SAGA_COMPENSATION_FAILED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-sagas.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-saga-compensation-failed"
  },
  {
    "code": "SAGA_EFFECT_OUTSIDE_BOUNDARY",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-sagas.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-saga-effect-outside-boundary"
  },
  {
    "code": "SAGA_NESTING_UNSUPPORTED",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-sagas.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-saga-nesting-unsupported"
  },
  {
    "code": "SAGA_OUTCOME_UNKNOWN",
    "owner": "package:@applik8s/applik8s",
    "sources": [
      "packages/applik8s/src/application-sagas.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-saga-outcome-unknown"
  },
  {
    "code": "SCHEDULE_CADENCE_UNREPRESENTABLE",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-cadence-unrepresentable"
  },
  {
    "code": "SCHEDULE_CARDINALITY_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-cardinality-unsupported"
  },
  {
    "code": "SCHEDULE_LATENESS_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-lateness-unsupported"
  },
  {
    "code": "SCHEDULE_MISFIRE_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-misfire-unsupported"
  },
  {
    "code": "SCHEDULE_PRECISION_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-precision-unsupported"
  },
  {
    "code": "SCHEDULE_PROVIDER_UNIMPLEMENTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-provider-unimplemented"
  },
  {
    "code": "SCHEDULE_PROVIDER_UNRESOLVED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-provider-unresolved"
  },
  {
    "code": "SCHEDULE_TIMEZONE_UNSUPPORTED",
    "owner": "package:@applik8s/deployment-compiler",
    "sources": [
      "packages/deployment-compiler/src/provider-guarantees.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schedule-timezone-unsupported"
  },
  {
    "code": "SCHEMA_INVALID",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/applik8s/src/dns.ts",
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schema-invalid"
  },
  {
    "code": "SCHEMA_UNSUPPORTED",
    "owner": "workspace:cross-package",
    "sources": [
      "packages/core/src/common.ts",
      "packages/sdk/src/schema-runtime.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-schema-unsupported"
  },
  {
    "code": "SERIALIZATION_FAILED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-serialization-failed"
  },
  {
    "code": "SIGNED_ENVELOPE_ALGORITHM_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-algorithm-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_CRYPTO_UNAVAILABLE",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-crypto-unavailable"
  },
  {
    "code": "SIGNED_ENVELOPE_EXPIRED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-expired"
  },
  {
    "code": "SIGNED_ENVELOPE_ISSUED_AT_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-issued-at-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_KEY_ID_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-key-id-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_KEY_INVALID",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-key-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_KEY_UNKNOWN",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-key-unknown"
  },
  {
    "code": "SIGNED_ENVELOPE_LIFETIME_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-lifetime-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_MALFORMED",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-malformed"
  },
  {
    "code": "SIGNED_ENVELOPE_OVERSIZED",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-oversized"
  },
  {
    "code": "SIGNED_ENVELOPE_PAYLOAD_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-payload-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_PURPOSE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-purpose-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_SHAPE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-shape-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_SIGNATURE_INVALID",
    "owner": "package:@applik8s/runtime",
    "sources": [
      "packages/runtime/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-signature-invalid"
  },
  {
    "code": "SIGNED_ENVELOPE_VERSION_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/signed-envelope.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-signed-envelope-version-invalid"
  },
  {
    "code": "START_DUPLICATE_PACKAGE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-duplicate-package"
  },
  {
    "code": "START_DUPLICATE_PROFILE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-duplicate-profile"
  },
  {
    "code": "START_DUPLICATE_ROUTE",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-duplicate-route"
  },
  {
    "code": "START_GENERATOR_BUDGET",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-generator-budget"
  },
  {
    "code": "START_GENERATOR_PATH",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-generator-path"
  },
  {
    "code": "START_GENERATOR_UNPINNED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-generator-unpinned"
  },
  {
    "code": "START_IDENTITY_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-start.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-start-identity-invalid"
  },
  {
    "code": "STATUS_PATCH_FAILED",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/common.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-status-patch-failed"
  },
  {
    "code": "TELEMETRY_BAGGAGE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-telemetry.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-telemetry-baggage-invalid"
  },
  {
    "code": "TELEMETRY_ENVELOPE_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-telemetry.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-telemetry-envelope-invalid"
  },
  {
    "code": "TELEMETRY_IDENTITY_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-telemetry.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-telemetry-identity-invalid"
  },
  {
    "code": "TELEMETRY_METRIC_INVALID",
    "owner": "package:@applik8s/core",
    "sources": [
      "packages/core/src/application-telemetry.ts"
    ],
    "documentation": "docs-site/src/content/docs/reference/diagnostics.mdx#diagnostic-telemetry-metric-invalid"
  }
]) satisfies readonly PublicDiagnosticRecord[];
