import type { AnyResourceDefinition, Applik8sError, CanonicalHandlerAbiRegistry, CanonicalHandlerAbiSource, CanonicalHandlerAbiVersion, Diagnostic, DomainDataPolicy, GeneratedSchemaArtifact, HandlerAbiDefinition, HandlerId, JsonObject, LifecyclePlan, ManagedObjectSnapshot, OperatorDefinition, OperatorManifest, PayloadSchemaKind, Result, RuntimeAdapterCapabilities, RuntimeAdapterKind, RuntimeAdapterRequirement, RuntimePayloadSchemas, SchemaSourceRef, Sha256Digest } from '@applik8s/core';

export type UnsupportedDependencyKind = 'nativeModule' | 'filesystemAccess' | 'networkAccess' | 'environmentAccess' | 'dynamicImport' | 'nonDeterministicBuildInput' | 'unsupportedHostImport';
export interface CompileOptions { readonly entrypoint: string; readonly outDir?: string; readonly packageName?: string; readonly runtimeVersionRange: string; readonly handlerAbiVersion: CanonicalHandlerAbiVersion; readonly adapter: RuntimeAdapterKind; readonly adapterRequirements?: RuntimeAdapterRequirement; readonly portability: CompilePortabilityPolicy; }
export interface CompileResult { readonly manifest: OperatorManifest; readonly artifacts: OperatorArtifacts; readonly schemas: readonly GeneratedSchemaArtifact[]; readonly handlerAbi: HandlerAbiArtifact; readonly closureGraph: ClosureGraph; readonly adapterCapabilities?: RuntimeAdapterCapabilities; readonly diagnostics: readonly Diagnostic[]; }
export interface CompilePortabilityPolicy { readonly deterministicBuild: boolean; readonly allowEnvironmentAccess: boolean; readonly allowFilesystemAccess: boolean; readonly allowNetworkAccess: boolean; readonly allowedHostImports: readonly string[]; readonly sourceMaps: SourceMapPolicy; }
export interface SourceMapPolicy { readonly emit: boolean; readonly includeSourceContent: boolean; readonly redactPaths: boolean; }
export interface OperatorArtifacts { readonly manifestJsonPath: string; readonly handlerWasmPath: string; readonly handlerWitPath: string; readonly generatedCrdYamlPaths: readonly string[]; readonly generatedRbacYamlPath: string; readonly generatedServiceAccountYamlPath: string; readonly generatedDeploymentYamlPath: string; readonly generatedConfigMapYamlPath: string; readonly generatedImageDockerfilePath?: string; readonly generatedApplyScriptPath?: string; readonly sourceMapPath?: string; }
export interface ClosureGraph { readonly entrypoint: string; readonly handlers: readonly HandlerClosure[]; readonly modules: readonly ClosureModule[]; readonly unsupportedDependencies: readonly UnsupportedDependency[]; readonly hostImports: readonly string[]; }
export interface HandlerClosure { readonly handlerId: HandlerId; readonly exportName: string; readonly sourceFile: string; readonly reachableModules: readonly string[]; readonly capturedConstants: JsonObject; }
export interface ClosureModule { readonly specifier: string; readonly sourceFile: string; readonly digest: Sha256Digest; readonly kind: 'source' | 'dependency' | 'generated'; }
export interface UnsupportedDependency { readonly specifier: string; readonly kind: UnsupportedDependencyKind; readonly reason: string; readonly diagnostic: Diagnostic; }
export interface HandlerAbiArtifact { readonly definition: HandlerAbiDefinition; readonly witSource: string; readonly path: string; readonly digest: Sha256Digest; }
export interface HandlerAbiEmitter { canonicalSource(version: CanonicalHandlerAbiVersion): Result<CanonicalHandlerAbiSource>; canonicalRegistry(): Result<CanonicalHandlerAbiRegistry>; emitWit(definition: HandlerAbiDefinition | CanonicalHandlerAbiSource): Result<HandlerAbiArtifact>; validateDefinition(definition: HandlerAbiDefinition): Result<readonly Diagnostic[]>; }
export interface RuntimeAdapterCapabilityRegistry { capabilities(kind: RuntimeAdapterKind): Result<RuntimeAdapterCapabilities>; validate(requirement: RuntimeAdapterRequirement, capabilities: RuntimeAdapterCapabilities): Result<readonly Diagnostic[]>; }
export interface SchemaEmitter { emitResourceSchemas<TResource extends AnyResourceDefinition>(resource: TResource): Result<readonly GeneratedSchemaArtifact[]>; emitOperatorManifestSchema(operator: OperatorDefinition): Result<GeneratedSchemaArtifact>; emitRuntimePayloadSchemas(abi: HandlerAbiArtifact): Result<RuntimePayloadSchemas>; emitPayloadSchema(kind: PayloadSchemaKind): Result<GeneratedSchemaArtifact>; }
export interface SchemaCompatibilityChecker { validateSource(ref: SchemaSourceRef): Result<readonly Diagnostic[]>; validateGeneratedArtifact(artifact: GeneratedSchemaArtifact): Result<readonly Diagnostic[]>; }
export interface LifecyclePlanner { planInstall(manifest: OperatorManifest): Result<LifecyclePlan>; planUpgrade(current: OperatorManifest, next: OperatorManifest, observed: readonly ManagedObjectSnapshot[]): Result<LifecyclePlan>; planRollback(current: OperatorManifest, previous: OperatorManifest, observed: readonly ManagedObjectSnapshot[]): Result<LifecyclePlan>; planUninstallController(current: OperatorManifest, policy: DomainDataPolicy): Result<LifecyclePlan>; planDeleteDomainData(current: OperatorManifest, policy: DomainDataPolicy): Result<LifecyclePlan>; }
export interface ArtifactEmitter { emitGeneratedKubernetesYaml(result: CompileResult): Promise<Result<readonly string[]>>; emitHelm(result: CompileResult, outputDir: string): Promise<Result<readonly string[]>>; emitKustomize(result: CompileResult, outputDir: string): Promise<Result<readonly string[]>>; emitOciLayout(result: CompileResult, outputDir: string): Promise<Result<readonly string[]>>; emitOlmBundle(result: CompileResult, outputDir: string): Promise<Result<readonly string[]>>; }
export interface Compiler { discover(entrypoint: string): Promise<Result<readonly OperatorDefinition[]>>; compile(options: CompileOptions): Promise<Result<CompileResult>>; validate(result: CompileResult): Result<readonly Diagnostic[]>; }
export interface CompilerFactory { create(): Result<Compiler>; createPipeline(): Result<import('./pipeline/index.js').CompileOperatorPipeline>; }
export type CompilerError = Applik8sError;
