import { describeCharacterSuite, type CharacterScenario } from '../../testing/test/character.js';

const s = (name: string, userStory: string, arrange: readonly string[], act: readonly string[], assert: readonly string[]): CharacterScenario => ({ name, userStory, arrange, act, assert });

describeCharacterSuite('SDK authoring character tests', [
  s('creates a typed namespaced CRD from ArkType schemas', 'As an app developer, I define durable domain state with crd().', ['Define ImageJob with spec and status ArkType schemas.'], ['Call crd({ apiVersion, kind, spec, status }).'], ['Resource definition exposes apiVersion, kind, inferred plural, namespaced scope, schemas, status subresource, permissions, and event sources.']),
  s('creates a cluster-scoped CRD when requested', 'As a platform engineer, I model cluster-wide domain state.', ['Define ClusterTenant with scope Cluster.'], ['Call crd({ scope: "Cluster" }).'], ['Resource definition has cluster scope and resource factories do not require namespace.']),
  s('preserves explicit plural and printer columns', 'As a CRD author, I control Kubernetes-facing names and kubectl output.', ['Define a CRD with plural and additionalPrinterColumns.'], ['Create the resource definition.'], ['Plural and printer columns are available for CRD generation.']),
  s('supports status conventions without forcing one status shape', 'As an operator author, I expose interoperable status while preserving domain fields.', ['Define status with phase, observedGeneration, conditions, message.'], ['Pass statusConvention to crd().'], ['Status convention metadata points to the configured fields.']),
  s('rejects non-structural Kubernetes schemas', 'As a user, I get build-time feedback for schemas Kubernetes cannot validate.', ['Define a schema with unsupported union or non-structural shape.'], ['Create or compile the CRD.'], ['The operation fails with actionable schema diagnostics.']),
  s('resource factories emit Kubernetes-shaped objects', 'As a user, I instantiate CRDs like normal resources.', ['Create ImageJob CRD.'], ['Call ImageJob({ name, namespace, labels, annotations, spec }).'], ['The object has apiVersion, kind, metadata, spec, labels, annotations, and no required status input.']),
  s('deployed operators expose uppercase and lowercase CRD factories', 'As a TypeScript user, I use ergonomic resource factories from an installed operator.', ['Define imagePipeline operator with ImageJob.'], ['Call imagePipeline({ namespace: "media" }).ImageJob(...) and .imageJob(...).'], ['Both factories produce equivalent resources scoped to the deployment namespace.']),
  s('operator accepts only handlers for declared resources', 'As an operator author, I get type-safe handler registration.', ['Define ImageJob and OtherJob CRDs.'], ['Create operator with resources { ImageJob } and a handler for OtherJob.'], ['Type/runtime validation rejects the undeclared handler.']),
  s('operator preserves permissions, capabilities, trust, and effect policy', 'As a platform engineer, I inspect least-privilege operator intent.', ['Define explicit RBAC, external capabilities, trustLevel, and effects.'], ['Call operator({ ... }).'], ['The operator definition preserves all security and effect metadata.']),
  s('callable operator returns deployed CRD factories without pretending to install', 'As a TypeScript user, I instantiate operator CRDs ergonomically before handing installation to compiler or TypeKro artifacts.', ['Define imagePipeline.'], ['Call imagePipeline({ namespace: "media", replicas: 2 }).'], ['The result includes namespace, crdFactories, resources, and callable resource aliases, while install resources come from compiled manifests or TypeKro composition.']),
  s('multi-operator bundling stays out of the v0.1 SDK surface', 'As a user, I do not see packaging APIs before lifecycle and RBAC semantics are real.', ['Define billing, tenants, and images operators.'], ['Inspect the public SDK surface.'], ['No operatorBundle API is exposed until multi-operator packaging has explicit lifecycle semantics.']),
  s('proxy handlers record status draft writes', 'As a handler author, I write normal object mutation syntax.', ['Define ImageJob.on.reconcile(async job => job.status.phase = "Processing").'], ['Invoke the handler through the test harness.'], ['The normalized operation plan includes a status operation for phase Processing.']),
  s('proxy handlers read draft status after writes', 'As a handler author, I can branch on status values I just set.', ['Write job.status.phase and then read job.status.phase.'], ['Run the handler.'], ['The read observes the draft value, not only the original object status.']),
  s('proxy handlers apply Kubernetes objects', 'As a handler author, I declare desired child resources.', ['Create a handler that calls job.apply(job.batch.Job(...)).'], ['Run the handler.'], ['The normalized plan includes an apply operation and no live cluster mutation occurs inside the handler.']),
  s('proxy handlers record delete, patch, events, finalizers, and requeue', 'As a handler author, I can express complete reconcile intent.', ['Create a handler using delete, patch, events.warning, finalizers.add, and requeue.'], ['Run the handler.'], ['The normalized plan includes each operation with stable serializable shape.']),
  s('proxy-recorded operations merge with explicit handler results', 'As a library author, I can mix ergonomic proxies with explicit returns.', ['Write status through proxy and return { events, requeue }.'], ['Run the handler.'], ['The final handler result contains proxy status plus returned events and requeue.']),
  s('context handlers normalize to the same operation-plan shape as proxy handlers', 'As an advanced user, I can use lower-level context APIs without changing runtime semantics.', ['Write equivalent proxy and context handlers.'], ['Invoke both handlers with the same object.'], ['Both produce equivalent normalized operation plans.']),
  s('external HTTP capabilities are declared by descriptor not captured clients', 'As a security-conscious user, I pass external access explicitly.', ['Declare stripe: external.http({ baseUrl, auth: secretRef(...) }).'], ['Use invoice.capabilities.stripe.post in a handler.'], ['Manifest records capability descriptor and handler artifact does not embed secret material.']),
  s('missing and denied capabilities fail explicitly', 'As an operator user, I see capability configuration failures clearly.', ['Run a handler that calls a missing or denied capability.'], ['Invoke through runtime/test harness.'], ['The failure is CAPABILITY_MISSING or CAPABILITY_DENIED with object and handler context.']),
]);
