import type { AnyKubernetesObject, AnyResourceDefinition, CapabilityClientSet, CapabilityPayload, ConditionStatus, ExternalEffectRecord, HandlerAbiDefinition, HandlerEventType, HandlerResult, JsonObject, JsonPatch, JsonValue, LifecyclePlan, ManagedByMetadata, NormalizedOperationPlan, ObjectRef, OperatorDefinition, OperatorManifest, PermissionRule, ReplayRecord, Result } from '@applik8s/core';

export interface OperatorTestHarness { given(...objects: readonly AnyKubernetesObject[]): OperatorTestHarness; givenCapability(name: string, capability: FakeCapability): OperatorTestHarness; reconcile(ref: ObjectRef): Promise<Result<HandlerResult>>; run(options?: TestRunOptions): Promise<Result<TestRunResult>>; expectApply(match: AnyKubernetesObject | ResourceMatcher): OperatorTestHarness; expectPatch(ref: ObjectRef, patch?: JsonPatch): OperatorTestHarness; expectDelete(ref: ObjectRef): OperatorTestHarness; expectFinalizer(finalizer: string, operation?: 'add' | 'remove'): OperatorTestHarness; expectStatus(status: JsonObject): OperatorTestHarness; expectCondition(reason: string, status?: ConditionStatus): OperatorTestHarness; expectExternalEffect(effect: ExternalEffectRecord): OperatorTestHarness; expectEvent(reason: string): OperatorTestHarness; expectRbac(rule: PermissionRule): OperatorTestHarness; expectManifest(manifest: ManifestMatcher): OperatorTestHarness; expectSchema(resourceKind: string, assertion: SchemaMatcher): OperatorTestHarness; expectAbi(abi: HandlerAbiDefinition): OperatorTestHarness; expectManagedBy(metadata: ManagedByMetadata): OperatorTestHarness; expectLifecycle(plan: LifecyclePlan): OperatorTestHarness; expectRequeue(afterSeconds?: number): OperatorTestHarness; expectNoop(): OperatorTestHarness; }
export interface TestRunOptions { readonly reconcile?: ObjectRef; readonly event?: HandlerEventType; readonly failFast?: boolean; }
export interface TestRunResult { readonly handlerResult?: HandlerResult; readonly normalizedPlan?: NormalizedOperationPlan; readonly assertionsPassed: number; readonly assertionFailures: readonly TestAssertionFailure[]; }
export interface TestAssertionFailure { readonly expectation: string; readonly message: string; readonly actual?: JsonValue; }
export interface FakeCapability { readonly responses: readonly FakeCapabilityResponse[]; }
export interface FakeCapabilityResponse { readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE'; readonly path: string; readonly response: CapabilityPayload; }
export interface ResourceMatcher { readonly apiVersion?: string; readonly kind?: string; readonly name?: string; readonly namespace?: string; readonly spec?: JsonObject; }
export interface ManifestMatcher { readonly manifest?: OperatorManifest; readonly operatorName?: string; readonly handlerAbi?: string; readonly ownedCrds?: readonly string[]; }
export interface SchemaMatcher { readonly structural: boolean; readonly preservesUnknownFields?: boolean; readonly requiredFields?: readonly string[]; }
export interface ReplayFixture { readonly inputPath: string; readonly expectedResultPath?: string; }
export interface ReplayHarness { replay(fixture: ReplayFixture): Promise<Result<ReplayRecord>>; }
export interface OperatorDefinitionSource<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>> { readonly definition: OperatorDefinition<TCapabilities, TResources>; }
export type TestOperatorTarget<TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>> = OperatorDefinition<TCapabilities, TResources> | OperatorDefinitionSource<TCapabilities, TResources>;
export type TestOperatorFunction = <TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>>(operator: TestOperatorTarget<TCapabilities, TResources>) => OperatorTestHarness;
export type ReplayOperatorFunction = <TCapabilities extends CapabilityClientSet = CapabilityClientSet, TResources extends Readonly<Record<string, AnyResourceDefinition<TCapabilities>>> = Readonly<Record<string, AnyResourceDefinition<TCapabilities>>>>(operator: TestOperatorTarget<TCapabilities, TResources>) => ReplayHarness;
export interface Applik8sTestingApi { readonly testOperator: TestOperatorFunction; readonly replayOperator: ReplayOperatorFunction; }
