import { describeCharacterSuite, type CharacterScenario } from '../../testing/test/character.js';

const s = (name: string, userStory: string, arrange: readonly string[], act: readonly string[], assert: readonly string[]): CharacterScenario => ({ name, userStory, arrange, act, assert });

describeCharacterSuite('compiler build-pipeline character tests', [
  s('discovers exported operators from an entrypoint', 'As a builder, I point applik8s at source and get operator definitions.', ['Create an entrypoint exporting imagePipeline and billing operators.'], ['Run compiler.discover(entrypoint).'], ['Only exported callable operators are returned with source locations.']),
  s('reports duplicate operator names', 'As a user, I get deterministic diagnostics for invalid builds.', ['Export two operators with the same name.'], ['Run discovery or compile.'], ['The build fails with duplicate operator diagnostics.']),
  s('assigns stable handler IDs', 'As a runtime operator, I need stable handler identity across builds.', ['Define handlers in stable source order.'], ['Compile twice without source changes.'], ['Handler IDs and exports are stable.']),
  s('bundles local helper functions and captured constants', 'As a TypeScript developer, I write ordinary helper code.', ['A handler calls helper functions and closes over constants.'], ['Compile the operator.'], ['Closure graph includes helper modules and captured constants.']),
  s('bundles pure npm dependencies', 'As a developer, I reuse normal JavaScript libraries when they fit the runtime.', ['A handler imports a pure JS dependency.'], ['Compile with bundling.'], ['The dependency appears in the closure graph and no unsupported dependency diagnostic is emitted.']),
  s('rejects native modules by default', 'As a platform engineer, I avoid runtime surprises in the cluster.', ['A handler imports a native module.'], ['Compile with default portability policy.'], ['Compile fails with unsupported nativeModule diagnostics.']),
  s('rejects filesystem, environment, network, and dynamic import access by default', 'As a portability-focused user, I see ambient assumptions before deployment.', ['Handlers use fs, process.env, raw network, and import().'], ['Compile with default portability policy.'], ['Compile fails with separate actionable diagnostics for each unsupported assumption.']),
  s('emits a WASM component and WIT handler ABI', 'As a runtime, I need a stable deployable artifact.', ['Define a minimal operator.'], ['Compile to an output directory.'], ['CompileResult includes handlerWasmPath, handlerWitPath, ABI artifact, and digest.']),
  s('emits canonical runtime payload schemas', 'As a runtime author, I validate every ABI payload.', ['Compile an operator for applik8s.handler/v1alpha1.'], ['Ask schemaEmitter for runtime payload schemas.'], ['Schemas exist for handler input, normalized plan, operator manifest, handler error, capability request, and capability response.']),
  s('rejects non-WASM runtime adapters', 'As a project maintainer, I keep one deployable execution path.', ['Configure compile with a non-WASM adapter value.'], ['Run compile.'], ['The type system or compiler rejects the adapter.']),
  s('records JavaScript feature requirements', 'As a runtime, I validate that handlers can execute before starting.', ['Compile handlers using closures, async, promises, and Proxy.'], ['Inspect the manifest adapterRequirements.'], ['Requirements list the JavaScript features and wasmComponentModel true.']),
  s('proves ComponentizeJS can run async and Proxy handlers', 'As a product builder, I validate the key toolchain bet before relying on it.', ['Bundle a TypeScript handler using async/await and ES6 Proxy.'], ['Componentize it and invoke through Wasmtime.'], ['Invocation returns a valid handler result through the canonical ABI.']),
  s('generates structural CRDs with status subresources', 'As a Kubernetes user, I can apply generated manifests safely.', ['Compile CRDs with spec, status, columns, and versions.'], ['Emit Kubernetes YAML.'], ['Generated CRDs are structural and include status subresource and printer columns.']),
  s('infers and emits RBAC', 'As a cluster admin, I can inspect least privilege before install.', ['Handlers watch resources, patch status, apply Jobs, delete targets, record events, and use leader election.'], ['Compile and emit RBAC.'], ['RBAC includes watch, status, apply, delete, events, and lease permissions.']),
  s('emits install resources with bundle identity metadata', 'As an operator user, I can audit what is running.', ['Compile an operator bundle.'], ['Emit deployment, service account, config map, and manifest.'], ['Generated resources include managed-by, bundle digest, runtime ABI, and operator identity metadata.']),
  s('plans safe install, upgrade, rollback, and uninstall', 'As a platform engineer, I manage operator lifecycle explicitly.', ['Prepare current, next, and previous manifests plus observed objects.'], ['Run lifecycle planner methods.'], ['Plans report compatibility decisions and distinguish controller uninstall from domain data deletion.']),
  s('fails unsafe destructive lifecycle actions closed', 'As a user, I am protected from accidental CRD data deletion.', ['Plan domain data deletion without explicit destructive confirmation.'], ['Run lifecycle planner.'], ['The plan reports destructive action requiring explicit confirmation.']),
]);
